// Task Source — IT Asset Tracker seed data (from Assets Details spreadsheet)
(function () {
  const DEPARTMENTS = ["Sales","Payments","Smart Key","LGD Purchase","Accounts","Watches","Purchase","Mindhives","Sales Outbound","Surya","Credit","Shipping","Cheques","MIS/IT","Buying","Shared Pool"];
  const ASSET_TYPES = ["Desktop", "Laptop"];
  // hue per department for badge tints
  const DEPT_HUE = {
    "Sales": 248,
    "Payments": 210,
    "Smart Key": 168,
    "LGD Purchase": 28,
    "Accounts": 330,
    "Watches": 12,
    "Purchase": 200,
    "Mindhives": 272,
    "Sales Outbound": 140,
    "Surya": 52,
    "Credit": 92,
    "Shipping": 304,
    "Cheques": 238,
    "MIS/IT": 180,
    "Buying": 358,
    "Shared Pool": 248
  };
  const ASSETS = [
   {
    "id": "TS-PC-134",
    "pseudo": "Sid",
    "shared": false,
    "dept": "LGD Purchase",
    "type": "Desktop",
    "cpu": null,
    "ram": null,
    "hdd": null,
    "mon1": null,
    "mon2": null,
    "monitors": "—",
    "headphone": true,
    "speaker": true,
    "ipPhone": false,
    "webcam": false,
    "mobileStand": false,
    "whatsapp": false,
    "nextiva": false
   },
   {
    "id": "TS-PC-01",
    "pseudo": "Jasper",
    "shared": false,
    "dept": "LGD Purchase",
    "type": "Desktop",
    "cpu": null,
    "ram": null,
    "hdd": null,
    "mon1": null,
    "mon2": null,
    "monitors": "—",
    "headphone": true,
    "speaker": false,
    "ipPhone": false,
    "webcam": false,
    "mobileStand": false,
    "whatsapp": false,
    "nextiva": false
   },
   {
    "id": "TS-PC-137",
    "pseudo": "Louis",
    "shared": false,
    "dept": "LGD Purchase",
    "type": "Desktop",
    "cpu": null,
    "ram": null,
    "hdd": null,
    "mon1": null,
    "mon2": null,
    "monitors": "—",
    "headphone": false,
    "speaker": true,
    "ipPhone": false,
    "webcam": false,
    "mobileStand": true,
    "whatsapp": false,
    "nextiva": false
   },
   {
    "id": "TS-PC-135",
    "pseudo": "Freddy",
    "shared": false,
    "dept": "LGD Purchase",
    "type": "Desktop",
    "cpu": null,
    "ram": null,
    "hdd": null,
    "mon1": null,
    "mon2": null,
    "monitors": "—",
    "headphone": true,
    "speaker": true,
    "ipPhone": false,
    "webcam": false,
    "mobileStand": true,
    "whatsapp": false,
    "nextiva": false
   },
   {
    "id": "TS-PC-114",
    "pseudo": "Jim",
    "shared": false,
    "dept": "LGD Purchase",
    "type": "Desktop",
    "cpu": null,
    "ram": null,
    "hdd": null,
    "mon1": null,
    "mon2": null,
    "monitors": "—",
    "headphone": true,
    "speaker": true,
    "ipPhone": false,
    "webcam": false,
    "mobileStand": false,
    "whatsapp": false,
    "nextiva": false
   },
   {
    "id": "TS-PC-110",
    "pseudo": "Day-Shift PC",
    "shared": true,
    "dept": "LGD Purchase",
    "type": "Desktop",
    "cpu": null,
    "ram": null,
    "hdd": null,
    "mon1": null,
    "mon2": null,
    "monitors": "—",
    "headphone": true,
    "speaker": false,
    "ipPhone": false,
    "webcam": false,
    "mobileStand": false,
    "whatsapp": false,
    "nextiva": false
   },
   {
    "id": "TS-PC-139",
    "pseudo": "Justin",
    "shared": false,
    "dept": "LGD Purchase",
    "type": "Desktop",
    "cpu": null,
    "ram": null,
    "hdd": null,
    "mon1": null,
    "mon2": null,
    "monitors": "—",
    "headphone": true,
    "speaker": false,
    "ipPhone": false,
    "webcam": false,
    "mobileStand": false,
    "whatsapp": false,
    "nextiva": false
   },
   {
    "id": "TS-PC-133",
    "pseudo": "Kenny",
    "shared": false,
    "dept": "LGD Purchase",
    "type": "Desktop",
    "cpu": null,
    "ram": null,
    "hdd": null,
    "mon1": null,
    "mon2": null,
    "monitors": "—",
    "headphone": true,
    "speaker": true,
    "ipPhone": false,
    "webcam": false,
    "mobileStand": false,
    "whatsapp": false,
    "nextiva": false
   },
   {
    "id": "TS-PC-129",
    "pseudo": "Day-Shift PC",
    "shared": true,
    "dept": "LGD Purchase",
    "type": "Desktop",
    "cpu": null,
    "ram": null,
    "hdd": null,
    "mon1": null,
    "mon2": null,
    "monitors": "—",
    "headphone": false,
    "speaker": false,
    "ipPhone": false,
    "webcam": false,
    "mobileStand": false,
    "whatsapp": false,
    "nextiva": false
   },
   {
    "id": "TS-PC-130",
    "pseudo": "Glenn",
    "shared": false,
    "dept": "LGD Purchase",
    "type": "Desktop",
    "cpu": null,
    "ram": null,
    "hdd": null,
    "mon1": null,
    "mon2": null,
    "monitors": "—",
    "headphone": true,
    "speaker": true,
    "ipPhone": false,
    "webcam": false,
    "mobileStand": false,
    "whatsapp": false,
    "nextiva": false
   },
   {
    "id": "TS-PC-131",
    "pseudo": "Joseph",
    "shared": false,
    "dept": "LGD Purchase",
    "type": "Desktop",
    "cpu": null,
    "ram": null,
    "hdd": null,
    "mon1": null,
    "mon2": null,
    "monitors": "—",
    "headphone": true,
    "speaker": true,
    "ipPhone": false,
    "webcam": false,
    "mobileStand": true,
    "whatsapp": false,
    "nextiva": false
   },
   {
    "id": "TS-PC-132",
    "pseudo": "Monika",
    "shared": false,
    "dept": "LGD Purchase",
    "type": "Desktop",
    "cpu": null,
    "ram": null,
    "hdd": null,
    "mon1": null,
    "mon2": null,
    "monitors": "—",
    "headphone": true,
    "speaker": true,
    "ipPhone": false,
    "webcam": false,
    "mobileStand": false,
    "whatsapp": false,
    "nextiva": false
   },
   {
    "id": "TS-PC-137",
    "pseudo": "Mathew",
    "shared": false,
    "dept": "LGD Purchase",
    "type": "Desktop",
    "cpu": null,
    "ram": null,
    "hdd": null,
    "mon1": null,
    "mon2": null,
    "monitors": "—",
    "headphone": true,
    "speaker": true,
    "ipPhone": false,
    "webcam": false,
    "mobileStand": true,
    "whatsapp": false,
    "nextiva": false
   },
   {
    "id": "TS-PC-141",
    "pseudo": "Harvey",
    "shared": false,
    "dept": "LGD Purchase",
    "type": "Desktop",
    "cpu": null,
    "ram": null,
    "hdd": null,
    "mon1": null,
    "mon2": null,
    "monitors": "—",
    "headphone": true,
    "speaker": false,
    "ipPhone": false,
    "webcam": false,
    "mobileStand": true,
    "whatsapp": false,
    "nextiva": false
   },
   {
    "id": "TS-PC-127",
    "pseudo": "Bella",
    "shared": false,
    "dept": "Sales",
    "type": "Desktop",
    "cpu": null,
    "ram": null,
    "hdd": null,
    "mon1": null,
    "mon2": null,
    "monitors": "—",
    "headphone": true,
    "speaker": true,
    "ipPhone": false,
    "webcam": false,
    "mobileStand": true,
    "whatsapp": false,
    "nextiva": false
   },
   {
    "id": "TS-PC-123",
    "pseudo": "Flora",
    "shared": false,
    "dept": "Sales",
    "type": "Desktop",
    "cpu": null,
    "ram": null,
    "hdd": null,
    "mon1": null,
    "mon2": null,
    "monitors": "—",
    "headphone": true,
    "speaker": true,
    "ipPhone": false,
    "webcam": false,
    "mobileStand": true,
    "whatsapp": false,
    "nextiva": false
   },
   {
    "id": "TS-PC-125",
    "pseudo": "Ranjeet Kaka",
    "shared": false,
    "dept": "Sales",
    "type": "Desktop",
    "cpu": null,
    "ram": null,
    "hdd": null,
    "mon1": null,
    "mon2": null,
    "monitors": "—",
    "headphone": true,
    "speaker": true,
    "ipPhone": false,
    "webcam": false,
    "mobileStand": false,
    "whatsapp": false,
    "nextiva": false
   },
   {
    "id": "TS-PC-128",
    "pseudo": "Billy",
    "shared": false,
    "dept": "LGD Purchase",
    "type": "Desktop",
    "cpu": null,
    "ram": null,
    "hdd": null,
    "mon1": null,
    "mon2": null,
    "monitors": "—",
    "headphone": true,
    "speaker": true,
    "ipPhone": false,
    "webcam": false,
    "mobileStand": false,
    "whatsapp": false,
    "nextiva": false
   },
   {
    "id": "TS-PC-124",
    "pseudo": "Ammy",
    "shared": false,
    "dept": "LGD Purchase",
    "type": "Desktop",
    "cpu": null,
    "ram": null,
    "hdd": null,
    "mon1": null,
    "mon2": null,
    "monitors": "—",
    "headphone": true,
    "speaker": false,
    "ipPhone": false,
    "webcam": false,
    "mobileStand": false,
    "whatsapp": false,
    "nextiva": false
   },
   {
    "id": "TS-PC-39",
    "pseudo": "James",
    "shared": false,
    "dept": "Accounts",
    "type": "Desktop",
    "cpu": null,
    "ram": null,
    "hdd": null,
    "mon1": null,
    "mon2": null,
    "monitors": "—",
    "headphone": false,
    "speaker": false,
    "ipPhone": false,
    "webcam": false,
    "mobileStand": false,
    "whatsapp": false,
    "nextiva": false
   },
   {
    "id": "TS-PC-181",
    "pseudo": "Denver",
    "shared": false,
    "dept": "Accounts",
    "type": "Desktop",
    "cpu": null,
    "ram": null,
    "hdd": null,
    "mon1": null,
    "mon2": null,
    "monitors": "—",
    "headphone": false,
    "speaker": false,
    "ipPhone": false,
    "webcam": false,
    "mobileStand": false,
    "whatsapp": false,
    "nextiva": false
   },
   {
    "id": "TS-PC-157",
    "pseudo": "Dino",
    "shared": false,
    "dept": "Accounts",
    "type": "Desktop",
    "cpu": null,
    "ram": null,
    "hdd": null,
    "mon1": null,
    "mon2": null,
    "monitors": "—",
    "headphone": false,
    "speaker": false,
    "ipPhone": false,
    "webcam": false,
    "mobileStand": false,
    "whatsapp": false,
    "nextiva": false
   },
   {
    "id": "TS-PC-154",
    "pseudo": "Philip",
    "shared": false,
    "dept": "Accounts",
    "type": "Desktop",
    "cpu": null,
    "ram": null,
    "hdd": null,
    "mon1": null,
    "mon2": null,
    "monitors": "—",
    "headphone": false,
    "speaker": false,
    "ipPhone": false,
    "webcam": false,
    "mobileStand": false,
    "whatsapp": false,
    "nextiva": false
   },
   {
    "id": "TS-PC-176",
    "pseudo": "Herry",
    "shared": false,
    "dept": "Accounts",
    "type": "Desktop",
    "cpu": null,
    "ram": null,
    "hdd": null,
    "mon1": null,
    "mon2": null,
    "monitors": "—",
    "headphone": false,
    "speaker": false,
    "ipPhone": false,
    "webcam": false,
    "mobileStand": false,
    "whatsapp": false,
    "nextiva": false
   },
   {
    "id": "TS-PC-189",
    "pseudo": "Micheal",
    "shared": false,
    "dept": "Accounts",
    "type": "Desktop",
    "cpu": null,
    "ram": null,
    "hdd": null,
    "mon1": null,
    "mon2": null,
    "monitors": "—",
    "headphone": true,
    "speaker": false,
    "ipPhone": true,
    "webcam": false,
    "mobileStand": false,
    "whatsapp": false,
    "nextiva": false
   },
   {
    "id": "TS-PC-158",
    "pseudo": "Adam",
    "shared": false,
    "dept": "Accounts",
    "type": "Desktop",
    "cpu": null,
    "ram": null,
    "hdd": null,
    "mon1": null,
    "mon2": null,
    "monitors": "—",
    "headphone": false,
    "speaker": false,
    "ipPhone": true,
    "webcam": false,
    "mobileStand": false,
    "whatsapp": false,
    "nextiva": false
   },
   {
    "id": "TS-PC-179",
    "pseudo": "Bruce",
    "shared": false,
    "dept": "Accounts",
    "type": "Desktop",
    "cpu": null,
    "ram": null,
    "hdd": null,
    "mon1": null,
    "mon2": null,
    "monitors": "—",
    "headphone": false,
    "speaker": false,
    "ipPhone": true,
    "webcam": false,
    "mobileStand": false,
    "whatsapp": false,
    "nextiva": false
   },
   {
    "id": "TS-PC-188",
    "pseudo": "Elena",
    "shared": false,
    "dept": "Accounts",
    "type": "Desktop",
    "cpu": null,
    "ram": null,
    "hdd": null,
    "mon1": null,
    "mon2": null,
    "monitors": "—",
    "headphone": true,
    "speaker": false,
    "ipPhone": false,
    "webcam": false,
    "mobileStand": false,
    "whatsapp": false,
    "nextiva": false
   },
   {
    "id": "TS-PC-183",
    "pseudo": "Miller",
    "shared": false,
    "dept": "Accounts",
    "type": "Desktop",
    "cpu": null,
    "ram": null,
    "hdd": null,
    "mon1": null,
    "mon2": null,
    "monitors": "—",
    "headphone": false,
    "speaker": false,
    "ipPhone": false,
    "webcam": false,
    "mobileStand": false,
    "whatsapp": false,
    "nextiva": false
   },
   {
    "id": "TS-PC-66",
    "pseudo": "Morgan",
    "shared": false,
    "dept": "Accounts",
    "type": "Desktop",
    "cpu": null,
    "ram": null,
    "hdd": null,
    "mon1": null,
    "mon2": null,
    "monitors": "—",
    "headphone": false,
    "speaker": false,
    "ipPhone": false,
    "webcam": false,
    "mobileStand": false,
    "whatsapp": false,
    "nextiva": false
   },
   {
    "id": "TS-PC-153",
    "pseudo": "Max",
    "shared": false,
    "dept": "Accounts",
    "type": "Desktop",
    "cpu": null,
    "ram": null,
    "hdd": null,
    "mon1": null,
    "mon2": null,
    "monitors": "—",
    "headphone": true,
    "speaker": false,
    "ipPhone": false,
    "webcam": false,
    "mobileStand": false,
    "whatsapp": false,
    "nextiva": false
   },
   {
    "id": "TS-PC-160",
    "pseudo": "Jordan",
    "shared": false,
    "dept": "Accounts",
    "type": "Desktop",
    "cpu": null,
    "ram": null,
    "hdd": null,
    "mon1": null,
    "mon2": null,
    "monitors": "—",
    "headphone": false,
    "speaker": false,
    "ipPhone": false,
    "webcam": false,
    "mobileStand": false,
    "whatsapp": false,
    "nextiva": false
   },
   {
    "id": "TS-PC-184",
    "pseudo": "Sky",
    "shared": false,
    "dept": "Accounts",
    "type": "Desktop",
    "cpu": null,
    "ram": null,
    "hdd": null,
    "mon1": null,
    "mon2": null,
    "monitors": "—",
    "headphone": true,
    "speaker": false,
    "ipPhone": false,
    "webcam": false,
    "mobileStand": false,
    "whatsapp": false,
    "nextiva": false
   },
   {
    "id": "TS-PC-156",
    "pseudo": "Charlotte",
    "shared": false,
    "dept": "Accounts",
    "type": "Desktop",
    "cpu": null,
    "ram": null,
    "hdd": null,
    "mon1": null,
    "mon2": null,
    "monitors": "—",
    "headphone": true,
    "speaker": false,
    "ipPhone": false,
    "webcam": false,
    "mobileStand": false,
    "whatsapp": false,
    "nextiva": false
   },
   {
    "id": "TS-PC-32",
    "pseudo": "Austin",
    "shared": false,
    "dept": "Sales Outbound",
    "type": "Desktop",
    "cpu": null,
    "ram": null,
    "hdd": null,
    "mon1": null,
    "mon2": null,
    "monitors": "—",
    "headphone": true,
    "speaker": true,
    "ipPhone": false,
    "webcam": false,
    "mobileStand": false,
    "whatsapp": false,
    "nextiva": false
   },
   {
    "id": "TS-PC-122",
    "pseudo": "Jeremy",
    "shared": false,
    "dept": "Sales Outbound",
    "type": "Desktop",
    "cpu": null,
    "ram": null,
    "hdd": null,
    "mon1": null,
    "mon2": null,
    "monitors": "—",
    "headphone": true,
    "speaker": true,
    "ipPhone": false,
    "webcam": false,
    "mobileStand": true,
    "whatsapp": false,
    "nextiva": false
   },
   {
    "id": "TS-PC-121",
    "pseudo": "Emma",
    "shared": false,
    "dept": "Sales Outbound",
    "type": "Desktop",
    "cpu": null,
    "ram": null,
    "hdd": null,
    "mon1": null,
    "mon2": null,
    "monitors": "—",
    "headphone": false,
    "speaker": true,
    "ipPhone": false,
    "webcam": false,
    "mobileStand": false,
    "whatsapp": false,
    "nextiva": false
   },
   {
    "id": "TS-PC-111",
    "pseudo": "Hannah",
    "shared": false,
    "dept": "Sales Outbound",
    "type": "Desktop",
    "cpu": null,
    "ram": null,
    "hdd": null,
    "mon1": null,
    "mon2": null,
    "monitors": "—",
    "headphone": true,
    "speaker": false,
    "ipPhone": false,
    "webcam": false,
    "mobileStand": true,
    "whatsapp": false,
    "nextiva": false
   },
   {
    "id": "TS-PC-117",
    "pseudo": "Evelyn",
    "shared": false,
    "dept": "Sales Outbound",
    "type": "Desktop",
    "cpu": null,
    "ram": null,
    "hdd": null,
    "mon1": null,
    "mon2": null,
    "monitors": "—",
    "headphone": true,
    "speaker": true,
    "ipPhone": false,
    "webcam": false,
    "mobileStand": true,
    "whatsapp": false,
    "nextiva": false
   },
   {
    "id": "TS-PC-116",
    "pseudo": "Luke",
    "shared": false,
    "dept": "Sales Outbound",
    "type": "Desktop",
    "cpu": null,
    "ram": null,
    "hdd": null,
    "mon1": null,
    "mon2": null,
    "monitors": "—",
    "headphone": true,
    "speaker": true,
    "ipPhone": false,
    "webcam": false,
    "mobileStand": false,
    "whatsapp": false,
    "nextiva": false
   },
   {
    "id": "TS-PC-118",
    "pseudo": "Faith",
    "shared": false,
    "dept": "Sales Outbound",
    "type": "Desktop",
    "cpu": null,
    "ram": null,
    "hdd": null,
    "mon1": null,
    "mon2": null,
    "monitors": "—",
    "headphone": true,
    "speaker": true,
    "ipPhone": false,
    "webcam": false,
    "mobileStand": false,
    "whatsapp": false,
    "nextiva": false
   },
   {
    "id": "TS-PC-119",
    "pseudo": "Hope",
    "shared": false,
    "dept": "Sales Outbound",
    "type": "Desktop",
    "cpu": null,
    "ram": null,
    "hdd": null,
    "mon1": null,
    "mon2": null,
    "monitors": "—",
    "headphone": true,
    "speaker": false,
    "ipPhone": false,
    "webcam": false,
    "mobileStand": false,
    "whatsapp": false,
    "nextiva": false
   },
   {
    "id": "TS-PC-104",
    "pseudo": "Jayden",
    "shared": false,
    "dept": "Sales",
    "type": "Desktop",
    "cpu": null,
    "ram": null,
    "hdd": null,
    "mon1": null,
    "mon2": null,
    "monitors": "—",
    "headphone": true,
    "speaker": true,
    "ipPhone": false,
    "webcam": false,
    "mobileStand": false,
    "whatsapp": false,
    "nextiva": false
   },
   {
    "id": "TS-PC-99",
    "pseudo": "Noa",
    "shared": false,
    "dept": "Sales",
    "type": "Desktop",
    "cpu": null,
    "ram": null,
    "hdd": null,
    "mon1": null,
    "mon2": null,
    "monitors": "—",
    "headphone": true,
    "speaker": true,
    "ipPhone": false,
    "webcam": false,
    "mobileStand": false,
    "whatsapp": false,
    "nextiva": false
   },
   {
    "id": "TS-PC-100",
    "pseudo": "Skyler",
    "shared": false,
    "dept": "Sales",
    "type": "Desktop",
    "cpu": null,
    "ram": null,
    "hdd": null,
    "mon1": null,
    "mon2": null,
    "monitors": "—",
    "headphone": true,
    "speaker": true,
    "ipPhone": false,
    "webcam": false,
    "mobileStand": false,
    "whatsapp": false,
    "nextiva": false
   },
   {
    "id": "TS-PC-102",
    "pseudo": "Zoe",
    "shared": false,
    "dept": "Sales",
    "type": "Desktop",
    "cpu": null,
    "ram": null,
    "hdd": null,
    "mon1": null,
    "mon2": null,
    "monitors": "—",
    "headphone": true,
    "speaker": true,
    "ipPhone": false,
    "webcam": false,
    "mobileStand": true,
    "whatsapp": false,
    "nextiva": false
   },
   {
    "id": "TS-PC-98",
    "pseudo": "Walter",
    "shared": false,
    "dept": "Sales",
    "type": "Desktop",
    "cpu": null,
    "ram": null,
    "hdd": null,
    "mon1": null,
    "mon2": null,
    "monitors": "—",
    "headphone": true,
    "speaker": true,
    "ipPhone": false,
    "webcam": false,
    "mobileStand": true,
    "whatsapp": false,
    "nextiva": false
   },
   {
    "id": "TS-PC-143",
    "pseudo": "Stefan",
    "shared": false,
    "dept": "Sales",
    "type": "Desktop",
    "cpu": null,
    "ram": null,
    "hdd": null,
    "mon1": null,
    "mon2": null,
    "monitors": "—",
    "headphone": true,
    "speaker": true,
    "ipPhone": false,
    "webcam": false,
    "mobileStand": true,
    "whatsapp": false,
    "nextiva": false
   },
   {
    "id": "TS-PC-103",
    "pseudo": "Gabriel",
    "shared": false,
    "dept": "Sales",
    "type": "Desktop",
    "cpu": null,
    "ram": null,
    "hdd": null,
    "mon1": null,
    "mon2": null,
    "monitors": "—",
    "headphone": true,
    "speaker": false,
    "ipPhone": false,
    "webcam": false,
    "mobileStand": true,
    "whatsapp": false,
    "nextiva": false
   },
   {
    "id": "TS-PC-109",
    "pseudo": "Ashley",
    "shared": false,
    "dept": "Sales",
    "type": "Desktop",
    "cpu": null,
    "ram": null,
    "hdd": null,
    "mon1": null,
    "mon2": null,
    "monitors": "—",
    "headphone": true,
    "speaker": true,
    "ipPhone": false,
    "webcam": false,
    "mobileStand": true,
    "whatsapp": false,
    "nextiva": false
   },
   {
    "id": "TS-PC-106",
    "pseudo": "Lisa",
    "shared": false,
    "dept": "Sales",
    "type": "Desktop",
    "cpu": null,
    "ram": null,
    "hdd": null,
    "mon1": null,
    "mon2": null,
    "monitors": "—",
    "headphone": true,
    "speaker": true,
    "ipPhone": false,
    "webcam": false,
    "mobileStand": false,
    "whatsapp": false,
    "nextiva": false
   },
   {
    "id": "TS-PC-108",
    "pseudo": "Renee",
    "shared": false,
    "dept": "Sales",
    "type": "Desktop",
    "cpu": null,
    "ram": null,
    "hdd": null,
    "mon1": null,
    "mon2": null,
    "monitors": "—",
    "headphone": true,
    "speaker": false,
    "ipPhone": false,
    "webcam": false,
    "mobileStand": false,
    "whatsapp": false,
    "nextiva": false
   },
   {
    "id": "TS-PC-113",
    "pseudo": "Xavier",
    "shared": false,
    "dept": "Sales",
    "type": "Desktop",
    "cpu": null,
    "ram": null,
    "hdd": null,
    "mon1": null,
    "mon2": null,
    "monitors": "—",
    "headphone": true,
    "speaker": true,
    "ipPhone": false,
    "webcam": false,
    "mobileStand": false,
    "whatsapp": false,
    "nextiva": false
   },
   {
    "id": "TS-PC-185",
    "pseudo": "Marshall",
    "shared": false,
    "dept": "Sales",
    "type": "Desktop",
    "cpu": null,
    "ram": null,
    "hdd": null,
    "mon1": null,
    "mon2": null,
    "monitors": "—",
    "headphone": true,
    "speaker": true,
    "ipPhone": false,
    "webcam": false,
    "mobileStand": false,
    "whatsapp": false,
    "nextiva": false
   },
   {
    "id": "TS-PC-115",
    "pseudo": "Elsa",
    "shared": false,
    "dept": "Sales",
    "type": "Desktop",
    "cpu": null,
    "ram": null,
    "hdd": null,
    "mon1": null,
    "mon2": null,
    "monitors": "—",
    "headphone": true,
    "speaker": true,
    "ipPhone": false,
    "webcam": false,
    "mobileStand": false,
    "whatsapp": false,
    "nextiva": false
   },
   {
    "id": "TS-PC-112",
    "pseudo": "Robin",
    "shared": false,
    "dept": "Sales",
    "type": "Desktop",
    "cpu": null,
    "ram": null,
    "hdd": null,
    "mon1": null,
    "mon2": null,
    "monitors": "—",
    "headphone": true,
    "speaker": true,
    "ipPhone": false,
    "webcam": false,
    "mobileStand": false,
    "whatsapp": false,
    "nextiva": false
   },
   {
    "id": "TS-PC-101",
    "pseudo": "River",
    "shared": false,
    "dept": "Sales",
    "type": "Desktop",
    "cpu": null,
    "ram": null,
    "hdd": null,
    "mon1": null,
    "mon2": null,
    "monitors": "—",
    "headphone": true,
    "speaker": true,
    "ipPhone": false,
    "webcam": false,
    "mobileStand": false,
    "whatsapp": false,
    "nextiva": false
   },
   {
    "id": "TS-PC-140",
    "pseudo": "Rebecca",
    "shared": false,
    "dept": "Sales",
    "type": "Desktop",
    "cpu": null,
    "ram": null,
    "hdd": null,
    "mon1": null,
    "mon2": null,
    "monitors": "—",
    "headphone": true,
    "speaker": true,
    "ipPhone": false,
    "webcam": false,
    "mobileStand": false,
    "whatsapp": false,
    "nextiva": false
   },
   {
    "id": "TS-PC-42",
    "pseudo": "Arnold",
    "shared": false,
    "dept": "Credit",
    "type": "Desktop",
    "cpu": null,
    "ram": null,
    "hdd": null,
    "mon1": null,
    "mon2": null,
    "monitors": "—",
    "headphone": false,
    "speaker": true,
    "ipPhone": true,
    "webcam": false,
    "mobileStand": false,
    "whatsapp": false,
    "nextiva": false
   },
   {
    "id": "TS-PC-186",
    "pseudo": "Amanda",
    "shared": false,
    "dept": "Credit",
    "type": "Desktop",
    "cpu": null,
    "ram": null,
    "hdd": null,
    "mon1": null,
    "mon2": null,
    "monitors": "—",
    "headphone": true,
    "speaker": false,
    "ipPhone": true,
    "webcam": false,
    "mobileStand": false,
    "whatsapp": false,
    "nextiva": false
   },
   {
    "id": "TS-PC-44",
    "pseudo": "Maverick",
    "shared": false,
    "dept": "Credit",
    "type": "Desktop",
    "cpu": null,
    "ram": null,
    "hdd": null,
    "mon1": null,
    "mon2": null,
    "monitors": "—",
    "headphone": true,
    "speaker": true,
    "ipPhone": false,
    "webcam": false,
    "mobileStand": true,
    "whatsapp": false,
    "nextiva": false
   },
   {
    "id": "TS-PC-40",
    "pseudo": "Russel",
    "shared": false,
    "dept": "Credit",
    "type": "Desktop",
    "cpu": null,
    "ram": null,
    "hdd": null,
    "mon1": null,
    "mon2": null,
    "monitors": "—",
    "headphone": true,
    "speaker": false,
    "ipPhone": true,
    "webcam": false,
    "mobileStand": false,
    "whatsapp": false,
    "nextiva": false
   },
   {
    "id": "TS-PC-38",
    "pseudo": "Free",
    "shared": false,
    "dept": "Credit",
    "type": "Desktop",
    "cpu": null,
    "ram": null,
    "hdd": null,
    "mon1": null,
    "mon2": null,
    "monitors": "—",
    "headphone": false,
    "speaker": false,
    "ipPhone": false,
    "webcam": false,
    "mobileStand": false,
    "whatsapp": false,
    "nextiva": false
   },
   {
    "id": "TS-PC-187",
    "pseudo": "Clara",
    "shared": false,
    "dept": "Credit",
    "type": "Desktop",
    "cpu": null,
    "ram": null,
    "hdd": null,
    "mon1": null,
    "mon2": null,
    "monitors": "—",
    "headphone": true,
    "speaker": false,
    "ipPhone": false,
    "webcam": false,
    "mobileStand": false,
    "whatsapp": false,
    "nextiva": false
   },
   {
    "id": "TS-PC-150",
    "pseudo": "Arthur",
    "shared": false,
    "dept": "Cheques",
    "type": "Desktop",
    "cpu": null,
    "ram": null,
    "hdd": null,
    "mon1": null,
    "mon2": null,
    "monitors": "—",
    "headphone": true,
    "speaker": false,
    "ipPhone": false,
    "webcam": false,
    "mobileStand": false,
    "whatsapp": false,
    "nextiva": false
   },
   {
    "id": "TS-PC-34",
    "pseudo": "Amanda",
    "shared": false,
    "dept": "Cheques",
    "type": "Desktop",
    "cpu": null,
    "ram": null,
    "hdd": null,
    "mon1": null,
    "mon2": null,
    "monitors": "—",
    "headphone": false,
    "speaker": false,
    "ipPhone": false,
    "webcam": false,
    "mobileStand": false,
    "whatsapp": false,
    "nextiva": false
   },
   {
    "id": "TS-PC-27",
    "pseudo": "Ash",
    "shared": false,
    "dept": "Cheques",
    "type": "Desktop",
    "cpu": null,
    "ram": null,
    "hdd": null,
    "mon1": null,
    "mon2": null,
    "monitors": "—",
    "headphone": true,
    "speaker": false,
    "ipPhone": false,
    "webcam": false,
    "mobileStand": false,
    "whatsapp": false,
    "nextiva": false
   },
   {
    "id": "TS-PC-41",
    "pseudo": "Alec",
    "shared": false,
    "dept": "Cheques",
    "type": "Desktop",
    "cpu": null,
    "ram": null,
    "hdd": null,
    "mon1": null,
    "mon2": null,
    "monitors": "—",
    "headphone": false,
    "speaker": false,
    "ipPhone": false,
    "webcam": false,
    "mobileStand": false,
    "whatsapp": false,
    "nextiva": false
   },
   {
    "id": "TS-PC-159",
    "pseudo": "Alfred",
    "shared": false,
    "dept": "Cheques",
    "type": "Desktop",
    "cpu": null,
    "ram": null,
    "hdd": null,
    "mon1": null,
    "mon2": null,
    "monitors": "—",
    "headphone": false,
    "speaker": false,
    "ipPhone": true,
    "webcam": false,
    "mobileStand": false,
    "whatsapp": false,
    "nextiva": false
   },
   {
    "id": "TS-PC-92",
    "pseudo": "Edward",
    "shared": false,
    "dept": "Purchase",
    "type": "Desktop",
    "cpu": null,
    "ram": null,
    "hdd": null,
    "mon1": null,
    "mon2": null,
    "monitors": "—",
    "headphone": true,
    "speaker": true,
    "ipPhone": false,
    "webcam": false,
    "mobileStand": false,
    "whatsapp": false,
    "nextiva": false
   },
   {
    "id": "TS-PC-93",
    "pseudo": "Simon",
    "shared": false,
    "dept": "Purchase",
    "type": "Desktop",
    "cpu": null,
    "ram": null,
    "hdd": null,
    "mon1": null,
    "mon2": null,
    "monitors": "—",
    "headphone": true,
    "speaker": false,
    "ipPhone": true,
    "webcam": false,
    "mobileStand": true,
    "whatsapp": false,
    "nextiva": false
   },
   {
    "id": "TS-PC-94",
    "pseudo": "Hazel",
    "shared": false,
    "dept": "Purchase",
    "type": "Desktop",
    "cpu": null,
    "ram": null,
    "hdd": null,
    "mon1": null,
    "mon2": null,
    "monitors": "—",
    "headphone": true,
    "speaker": false,
    "ipPhone": false,
    "webcam": false,
    "mobileStand": false,
    "whatsapp": false,
    "nextiva": false
   },
   {
    "id": "TS-PC-96",
    "pseudo": "Jennifier",
    "shared": false,
    "dept": "Purchase",
    "type": "Desktop",
    "cpu": null,
    "ram": null,
    "hdd": null,
    "mon1": null,
    "mon2": null,
    "monitors": "—",
    "headphone": false,
    "speaker": true,
    "ipPhone": false,
    "webcam": false,
    "mobileStand": false,
    "whatsapp": false,
    "nextiva": false
   },
   {
    "id": "TS-PC-95",
    "pseudo": "Sam",
    "shared": false,
    "dept": "Purchase",
    "type": "Desktop",
    "cpu": null,
    "ram": null,
    "hdd": null,
    "mon1": null,
    "mon2": null,
    "monitors": "—",
    "headphone": false,
    "speaker": true,
    "ipPhone": true,
    "webcam": false,
    "mobileStand": false,
    "whatsapp": false,
    "nextiva": false
   },
   {
    "id": "TS-PC-177",
    "pseudo": "Finn",
    "shared": false,
    "dept": "Purchase",
    "type": "Desktop",
    "cpu": null,
    "ram": null,
    "hdd": null,
    "mon1": null,
    "mon2": null,
    "monitors": "—",
    "headphone": false,
    "speaker": false,
    "ipPhone": true,
    "webcam": false,
    "mobileStand": false,
    "whatsapp": false,
    "nextiva": false
   },
   {
    "id": "TS-PC-91",
    "pseudo": "Evan",
    "shared": false,
    "dept": "Purchase",
    "type": "Desktop",
    "cpu": null,
    "ram": null,
    "hdd": null,
    "mon1": null,
    "mon2": null,
    "monitors": "—",
    "headphone": false,
    "speaker": false,
    "ipPhone": true,
    "webcam": false,
    "mobileStand": false,
    "whatsapp": false,
    "nextiva": false
   },
   {
    "id": "TS-PC-90",
    "pseudo": "Nelson",
    "shared": false,
    "dept": "Purchase",
    "type": "Desktop",
    "cpu": null,
    "ram": null,
    "hdd": null,
    "mon1": null,
    "mon2": null,
    "monitors": "—",
    "headphone": false,
    "speaker": false,
    "ipPhone": false,
    "webcam": false,
    "mobileStand": false,
    "whatsapp": false,
    "nextiva": false
   },
   {
    "id": "TS-PC-89",
    "pseudo": "Logan",
    "shared": false,
    "dept": "Purchase",
    "type": "Desktop",
    "cpu": null,
    "ram": null,
    "hdd": null,
    "mon1": null,
    "mon2": null,
    "monitors": "—",
    "headphone": false,
    "speaker": false,
    "ipPhone": true,
    "webcam": false,
    "mobileStand": true,
    "whatsapp": false,
    "nextiva": false
   },
   {
    "id": "TS-PC-88",
    "pseudo": "Thomas",
    "shared": false,
    "dept": "Shipping",
    "type": "Desktop",
    "cpu": null,
    "ram": null,
    "hdd": null,
    "mon1": null,
    "mon2": null,
    "monitors": "—",
    "headphone": true,
    "speaker": false,
    "ipPhone": true,
    "webcam": false,
    "mobileStand": false,
    "whatsapp": false,
    "nextiva": false
   },
   {
    "id": "TS-PC-87",
    "pseudo": "Richard",
    "shared": false,
    "dept": "Shipping",
    "type": "Desktop",
    "cpu": null,
    "ram": null,
    "hdd": null,
    "mon1": null,
    "mon2": null,
    "monitors": "—",
    "headphone": true,
    "speaker": false,
    "ipPhone": false,
    "webcam": false,
    "mobileStand": false,
    "whatsapp": false,
    "nextiva": false
   },
   {
    "id": "TS-PC-182",
    "pseudo": "Alden",
    "shared": false,
    "dept": "Sales",
    "type": "Desktop",
    "cpu": null,
    "ram": null,
    "hdd": null,
    "mon1": null,
    "mon2": null,
    "monitors": "—",
    "headphone": true,
    "speaker": false,
    "ipPhone": false,
    "webcam": false,
    "mobileStand": false,
    "whatsapp": false,
    "nextiva": false
   },
   {
    "id": "TS-PC-86",
    "pseudo": "Mike",
    "shared": false,
    "dept": "Shipping",
    "type": "Desktop",
    "cpu": null,
    "ram": null,
    "hdd": null,
    "mon1": null,
    "mon2": null,
    "monitors": "—",
    "headphone": true,
    "speaker": false,
    "ipPhone": false,
    "webcam": false,
    "mobileStand": false,
    "whatsapp": false,
    "nextiva": false
   },
   {
    "id": "TS-PC-80",
    "pseudo": "Willium",
    "shared": false,
    "dept": "Shipping",
    "type": "Desktop",
    "cpu": null,
    "ram": null,
    "hdd": null,
    "mon1": null,
    "mon2": null,
    "monitors": "—",
    "headphone": true,
    "speaker": true,
    "ipPhone": true,
    "webcam": false,
    "mobileStand": false,
    "whatsapp": false,
    "nextiva": false
   },
   {
    "id": "TS-PC-81",
    "pseudo": "Joy",
    "shared": false,
    "dept": "Shipping",
    "type": "Desktop",
    "cpu": null,
    "ram": null,
    "hdd": null,
    "mon1": null,
    "mon2": null,
    "monitors": "—",
    "headphone": true,
    "speaker": true,
    "ipPhone": false,
    "webcam": false,
    "mobileStand": false,
    "whatsapp": false,
    "nextiva": false
   },
   {
    "id": "TS-PC-82",
    "pseudo": "Broke",
    "shared": false,
    "dept": "Shipping",
    "type": "Desktop",
    "cpu": null,
    "ram": null,
    "hdd": null,
    "mon1": null,
    "mon2": null,
    "monitors": "—",
    "headphone": true,
    "speaker": false,
    "ipPhone": false,
    "webcam": false,
    "mobileStand": true,
    "whatsapp": false,
    "nextiva": false
   },
   {
    "id": "TS-PC-173",
    "pseudo": "Tony",
    "shared": false,
    "dept": "Purchase",
    "type": "Desktop",
    "cpu": null,
    "ram": null,
    "hdd": null,
    "mon1": null,
    "mon2": null,
    "monitors": "—",
    "headphone": false,
    "speaker": false,
    "ipPhone": false,
    "webcam": false,
    "mobileStand": false,
    "whatsapp": false,
    "nextiva": false
   },
   {
    "id": "TS-PC-84",
    "pseudo": "Wattson",
    "shared": false,
    "dept": "Purchase",
    "type": "Desktop",
    "cpu": null,
    "ram": null,
    "hdd": null,
    "mon1": null,
    "mon2": null,
    "monitors": "—",
    "headphone": true,
    "speaker": false,
    "ipPhone": true,
    "webcam": false,
    "mobileStand": false,
    "whatsapp": false,
    "nextiva": false
   },
   {
    "id": "TS-PC-85",
    "pseudo": "Annie",
    "shared": false,
    "dept": "Purchase",
    "type": "Desktop",
    "cpu": null,
    "ram": null,
    "hdd": null,
    "mon1": null,
    "mon2": null,
    "monitors": "—",
    "headphone": true,
    "speaker": false,
    "ipPhone": false,
    "webcam": false,
    "mobileStand": false,
    "whatsapp": false,
    "nextiva": false
   },
   {
    "id": "TS-PC-79",
    "pseudo": "Gagan Jat",
    "shared": false,
    "dept": "Buying",
    "type": "Desktop",
    "cpu": null,
    "ram": null,
    "hdd": null,
    "mon1": null,
    "mon2": null,
    "monitors": "—",
    "headphone": false,
    "speaker": true,
    "ipPhone": false,
    "webcam": false,
    "mobileStand": false,
    "whatsapp": false,
    "nextiva": false
   },
   {
    "id": "TS-PC-78",
    "pseudo": "Zion",
    "shared": false,
    "dept": "Buying",
    "type": "Desktop",
    "cpu": null,
    "ram": null,
    "hdd": null,
    "mon1": null,
    "mon2": null,
    "monitors": "—",
    "headphone": true,
    "speaker": false,
    "ipPhone": false,
    "webcam": true,
    "mobileStand": false,
    "whatsapp": false,
    "nextiva": false
   },
   {
    "id": "TS-PC-77",
    "pseudo": "Day-Shift PC",
    "shared": true,
    "dept": "Shared Pool",
    "type": "Desktop",
    "cpu": null,
    "ram": null,
    "hdd": null,
    "mon1": null,
    "mon2": null,
    "monitors": "—",
    "headphone": false,
    "speaker": false,
    "ipPhone": false,
    "webcam": false,
    "mobileStand": false,
    "whatsapp": false,
    "nextiva": false
   },
   {
    "id": "TS-PC-76",
    "pseudo": "Rio New",
    "shared": false,
    "dept": "Surya",
    "type": "Desktop",
    "cpu": null,
    "ram": null,
    "hdd": null,
    "mon1": null,
    "mon2": null,
    "monitors": "—",
    "headphone": false,
    "speaker": false,
    "ipPhone": false,
    "webcam": false,
    "mobileStand": false,
    "whatsapp": false,
    "nextiva": false
   },
   {
    "id": "TS-PC-75",
    "pseudo": "Martine",
    "shared": false,
    "dept": "Surya",
    "type": "Desktop",
    "cpu": null,
    "ram": null,
    "hdd": null,
    "mon1": null,
    "mon2": null,
    "monitors": "—",
    "headphone": false,
    "speaker": false,
    "ipPhone": true,
    "webcam": false,
    "mobileStand": false,
    "whatsapp": false,
    "nextiva": false
   },
   {
    "id": "TS-PC-74",
    "pseudo": "Ethan",
    "shared": false,
    "dept": "Surya",
    "type": "Desktop",
    "cpu": null,
    "ram": null,
    "hdd": null,
    "mon1": null,
    "mon2": null,
    "monitors": "—",
    "headphone": false,
    "speaker": false,
    "ipPhone": true,
    "webcam": false,
    "mobileStand": false,
    "whatsapp": false,
    "nextiva": false
   },
   {
    "id": "TS-PC-68",
    "pseudo": "Davis",
    "shared": false,
    "dept": "Surya",
    "type": "Desktop",
    "cpu": null,
    "ram": null,
    "hdd": null,
    "mon1": null,
    "mon2": null,
    "monitors": "—",
    "headphone": false,
    "speaker": false,
    "ipPhone": true,
    "webcam": false,
    "mobileStand": false,
    "whatsapp": false,
    "nextiva": false
   },
   {
    "id": "TS-PC-69",
    "pseudo": "Rio Old",
    "shared": false,
    "dept": "Surya",
    "type": "Desktop",
    "cpu": null,
    "ram": null,
    "hdd": null,
    "mon1": null,
    "mon2": null,
    "monitors": "—",
    "headphone": false,
    "speaker": false,
    "ipPhone": false,
    "webcam": false,
    "mobileStand": true,
    "whatsapp": false,
    "nextiva": false
   },
   {
    "id": "TS-PC-71",
    "pseudo": "Day-Shift PC",
    "shared": true,
    "dept": "Surya",
    "type": "Desktop",
    "cpu": null,
    "ram": null,
    "hdd": null,
    "mon1": null,
    "mon2": null,
    "monitors": "—",
    "headphone": false,
    "speaker": false,
    "ipPhone": false,
    "webcam": false,
    "mobileStand": false,
    "whatsapp": false,
    "nextiva": false
   },
   {
    "id": "TS-PC-70",
    "pseudo": "Day-Shift PC",
    "shared": true,
    "dept": "Surya",
    "type": "Desktop",
    "cpu": null,
    "ram": null,
    "hdd": null,
    "mon1": null,
    "mon2": null,
    "monitors": "—",
    "headphone": false,
    "speaker": false,
    "ipPhone": false,
    "webcam": false,
    "mobileStand": false,
    "whatsapp": false,
    "nextiva": false
   },
   {
    "id": "TS-PC-72",
    "pseudo": "Day-Shift PC",
    "shared": true,
    "dept": "Surya",
    "type": "Desktop",
    "cpu": null,
    "ram": null,
    "hdd": null,
    "mon1": null,
    "mon2": null,
    "monitors": "—",
    "headphone": false,
    "speaker": false,
    "ipPhone": false,
    "webcam": false,
    "mobileStand": false,
    "whatsapp": false,
    "nextiva": false
   },
   {
    "id": "TS-PC-61",
    "pseudo": "Ella",
    "shared": false,
    "dept": "Payments",
    "type": "Desktop",
    "cpu": null,
    "ram": null,
    "hdd": null,
    "mon1": null,
    "mon2": null,
    "monitors": "—",
    "headphone": true,
    "speaker": false,
    "ipPhone": false,
    "webcam": false,
    "mobileStand": false,
    "whatsapp": false,
    "nextiva": false
   },
   {
    "id": "TS-PC-64",
    "pseudo": "Day-Shift PC",
    "shared": true,
    "dept": "Payments",
    "type": "Desktop",
    "cpu": null,
    "ram": null,
    "hdd": null,
    "mon1": null,
    "mon2": null,
    "monitors": "—",
    "headphone": true,
    "speaker": false,
    "ipPhone": false,
    "webcam": false,
    "mobileStand": false,
    "whatsapp": false,
    "nextiva": false
   },
   {
    "id": "TS-PC-54",
    "pseudo": "Rose",
    "shared": false,
    "dept": "Payments",
    "type": "Desktop",
    "cpu": null,
    "ram": null,
    "hdd": null,
    "mon1": null,
    "mon2": null,
    "monitors": "—",
    "headphone": true,
    "speaker": true,
    "ipPhone": false,
    "webcam": false,
    "mobileStand": false,
    "whatsapp": false,
    "nextiva": false
   },
   {
    "id": "TS-PC-53",
    "pseudo": "Erik",
    "shared": false,
    "dept": "Payments",
    "type": "Desktop",
    "cpu": null,
    "ram": null,
    "hdd": null,
    "mon1": null,
    "mon2": null,
    "monitors": "—",
    "headphone": true,
    "speaker": true,
    "ipPhone": false,
    "webcam": false,
    "mobileStand": false,
    "whatsapp": false,
    "nextiva": false
   },
   {
    "id": "TS-PC-200",
    "pseudo": "Day-Shift PC",
    "shared": true,
    "dept": "Payments",
    "type": "Desktop",
    "cpu": null,
    "ram": null,
    "hdd": null,
    "mon1": null,
    "mon2": null,
    "monitors": "—",
    "headphone": true,
    "speaker": false,
    "ipPhone": false,
    "webcam": false,
    "mobileStand": false,
    "whatsapp": false,
    "nextiva": false
   },
   {
    "id": "TS-PC-172",
    "pseudo": "Marcus",
    "shared": false,
    "dept": "Payments",
    "type": "Desktop",
    "cpu": null,
    "ram": null,
    "hdd": null,
    "mon1": null,
    "mon2": null,
    "monitors": "—",
    "headphone": true,
    "speaker": false,
    "ipPhone": false,
    "webcam": false,
    "mobileStand": false,
    "whatsapp": false,
    "nextiva": false
   },
   {
    "id": "TS-PC-62",
    "pseudo": "Aron",
    "shared": false,
    "dept": "Payments",
    "type": "Desktop",
    "cpu": null,
    "ram": null,
    "hdd": null,
    "mon1": null,
    "mon2": null,
    "monitors": "—",
    "headphone": true,
    "speaker": false,
    "ipPhone": true,
    "webcam": true,
    "mobileStand": false,
    "whatsapp": false,
    "nextiva": false
   },
   {
    "id": "TS-PC-56",
    "pseudo": "Asher",
    "shared": false,
    "dept": "Payments",
    "type": "Desktop",
    "cpu": "Intel i5 10th Gen",
    "ram": "16 GB",
    "hdd": "240 GB",
    "mon1": "5ZH4H9TX503946L",
    "mon2": "5ZUFH90W600578B",
    "monitors": "Dual",
    "headphone": true,
    "speaker": true,
    "ipPhone": false,
    "webcam": false,
    "mobileStand": false,
    "whatsapp": false,
    "nextiva": false
   },
   {
    "id": "TS-PC-57",
    "pseudo": "Nora",
    "shared": false,
    "dept": "Payments",
    "type": "Desktop",
    "cpu": "Intel i5 10th Gen",
    "ram": "16 GB",
    "hdd": "240 GB",
    "mon1": "5DNEH4TT802039F",
    "mon2": "BZUTH4TR401567Y",
    "monitors": "Dual",
    "headphone": true,
    "speaker": true,
    "ipPhone": false,
    "webcam": false,
    "mobileStand": false,
    "whatsapp": false,
    "nextiva": false
   },
   {
    "id": "TS-PC-138",
    "pseudo": "Lily",
    "shared": false,
    "dept": "Payments",
    "type": "Desktop",
    "cpu": "Intel i5 10th Gen",
    "ram": "16 GB",
    "hdd": "480 GB",
    "mon1": "4PWLHTW400286F",
    "mon2": "4PWLH4TT402442Y",
    "monitors": "Dual",
    "headphone": true,
    "speaker": true,
    "ipPhone": false,
    "webcam": false,
    "mobileStand": false,
    "whatsapp": false,
    "nextiva": false
   },
   {
    "id": "TS-PC-59",
    "pseudo": "Daisy",
    "shared": false,
    "dept": "Payments",
    "type": "Desktop",
    "cpu": "Intel i5 10th Gen",
    "ram": "8 GB",
    "hdd": "240 GB",
    "mon1": "5ZUFH9DW504474N",
    "mon2": "5ZFUH9DW501789X",
    "monitors": "Dual",
    "headphone": true,
    "speaker": false,
    "ipPhone": false,
    "webcam": false,
    "mobileStand": false,
    "whatsapp": false,
    "nextiva": false
   },
   {
    "id": "TS-PC-60",
    "pseudo": "Alvin",
    "shared": false,
    "dept": "Payments",
    "type": "Desktop",
    "cpu": "Intel i5 10th Gen",
    "ram": "8 GB",
    "hdd": "240 GB",
    "mon1": "4PWLH4TT500611M",
    "mon2": "5DNEH4TT802048L",
    "monitors": "Dual",
    "headphone": true,
    "speaker": false,
    "ipPhone": false,
    "webcam": false,
    "mobileStand": true,
    "whatsapp": false,
    "nextiva": false
   },
   {
    "id": "TS-PC-61",
    "pseudo": "Day-Shift PC",
    "shared": true,
    "dept": "Payments",
    "type": "Desktop",
    "cpu": "Intel i5 10th Gen",
    "ram": "8 GB",
    "hdd": "240 GB",
    "mon1": "4PWLH4TTA00138Z",
    "mon2": "4PWLH4TT500070P",
    "monitors": "Dual",
    "headphone": true,
    "speaker": false,
    "ipPhone": false,
    "webcam": false,
    "mobileStand": false,
    "whatsapp": false,
    "nextiva": false
   },
   {
    "id": "TS-PC-73",
    "pseudo": "Sandy",
    "shared": false,
    "dept": "Payments",
    "type": "Desktop",
    "cpu": "Intel i5 10th Gen",
    "ram": "8 GB",
    "hdd": "240 GB",
    "mon1": "5DNEH4TT803030H",
    "mon2": "5DNEH4TT804698M",
    "monitors": "Dual",
    "headphone": true,
    "speaker": false,
    "ipPhone": false,
    "webcam": false,
    "mobileStand": false,
    "whatsapp": false,
    "nextiva": false
   },
   {
    "id": "TS-PC-178",
    "pseudo": "Cooper",
    "shared": false,
    "dept": "Payments",
    "type": "Desktop",
    "cpu": "Intel i5 12th Gen",
    "ram": "16 GB",
    "hdd": "240 GB",
    "mon1": "4PWLH4TRB00559W",
    "mon2": "4PWLH4TTA00250B",
    "monitors": "Dual",
    "headphone": true,
    "speaker": true,
    "ipPhone": false,
    "webcam": false,
    "mobileStand": true,
    "whatsapp": false,
    "nextiva": false
   },
   {
    "id": "TS-PC-65",
    "pseudo": "Albert",
    "shared": false,
    "dept": "Payments",
    "type": "Desktop",
    "cpu": "Intel i5 9th Gen",
    "ram": "16 GB",
    "hdd": "480 GB",
    "mon1": "4PWLH4TTA00180D",
    "mon2": "4PWLH4TT500722X",
    "monitors": "Dual",
    "headphone": true,
    "speaker": false,
    "ipPhone": true,
    "webcam": false,
    "mobileStand": false,
    "whatsapp": false,
    "nextiva": false
   },
   {
    "id": "TS-PC-52",
    "pseudo": "Elvish",
    "shared": false,
    "dept": "Payments",
    "type": "Desktop",
    "cpu": "Intel i5 9th Gen",
    "ram": "8 GB",
    "hdd": "240 GB",
    "mon1": "5DNEH4TT801557X",
    "mon2": "4PWLH4TT501140H",
    "monitors": "Dual",
    "headphone": true,
    "speaker": false,
    "ipPhone": false,
    "webcam": false,
    "mobileStand": false,
    "whatsapp": false,
    "nextiva": false
   },
   {
    "id": "TS-PC-51",
    "pseudo": "Nick",
    "shared": false,
    "dept": "Payments",
    "type": "Desktop",
    "cpu": "Intel i5 10th Gen",
    "ram": "24 GB",
    "hdd": "240 GB",
    "mon1": "5ZUFH9DW600568Z",
    "mon2": "0DB9HNAT603603P",
    "monitors": "Dual",
    "headphone": true,
    "speaker": true,
    "ipPhone": true,
    "webcam": false,
    "mobileStand": false,
    "whatsapp": false,
    "nextiva": false
   },
   {
    "id": "TS-PC-50",
    "pseudo": "Darwin",
    "shared": false,
    "dept": "Payments",
    "type": "Desktop",
    "cpu": "Intel i5 10th Gen",
    "ram": "8 GB",
    "hdd": "240 GB",
    "mon1": "4PWLH4TT800023K",
    "mon2": "4PWLH4TW400275J",
    "monitors": "Dual",
    "headphone": true,
    "speaker": false,
    "ipPhone": false,
    "webcam": false,
    "mobileStand": false,
    "whatsapp": false,
    "nextiva": false
   },
   {
    "id": "TS-PC-29",
    "pseudo": "Kyle",
    "shared": false,
    "dept": "Mindhives",
    "type": "Desktop",
    "cpu": "Intel i5 12th Gen",
    "ram": "16 GB",
    "hdd": "450 GB / 2 TB",
    "mon1": "0WPLHNCV604246N",
    "mon2": "0WPLHNCY406N38D",
    "monitors": "Dual",
    "headphone": false,
    "speaker": false,
    "ipPhone": false,
    "webcam": false,
    "mobileStand": false,
    "whatsapp": false,
    "nextiva": false
   },
   {
    "id": "—",
    "pseudo": "Charlie",
    "shared": false,
    "dept": "Mindhives",
    "type": "Desktop",
    "cpu": "Mac Mini",
    "ram": null,
    "hdd": null,
    "mon1": "5ZHXH9TXA00297Z",
    "mon2": "7DU3H9DL101116V",
    "monitors": "Dual",
    "headphone": true,
    "speaker": false,
    "ipPhone": false,
    "webcam": false,
    "mobileStand": false,
    "whatsapp": false,
    "nextiva": false
   },
   {
    "id": "TS-PC-191",
    "pseudo": "Miles",
    "shared": false,
    "dept": "Mindhives",
    "type": "Desktop",
    "cpu": "Intel i5 10th Gen",
    "ram": "8 GB",
    "hdd": "240 GB",
    "mon1": "0WPLHNCY407086X",
    "mon2": "BZUTH4TN301043T",
    "monitors": "Dual",
    "headphone": false,
    "speaker": false,
    "ipPhone": false,
    "webcam": false,
    "mobileStand": false,
    "whatsapp": false,
    "nextiva": false
   },
   {
    "id": "TS-PC-192",
    "pseudo": "Jane",
    "shared": false,
    "dept": "Mindhives",
    "type": "Desktop",
    "cpu": "Intel i5 12th Gen",
    "ram": "16 GB",
    "hdd": "480 GB",
    "mon1": "7DU3H9DYA03067H",
    "mon2": "7DU3H9DYA03077W",
    "monitors": "Dual",
    "headphone": false,
    "speaker": false,
    "ipPhone": false,
    "webcam": false,
    "mobileStand": false,
    "whatsapp": false,
    "nextiva": false
   },
   {
    "id": "TS-PC-24",
    "pseudo": "Peter",
    "shared": false,
    "dept": "Mindhives",
    "type": "Desktop",
    "cpu": "Intel i5 12th Gen",
    "ram": "16 GB",
    "hdd": "480 GB",
    "mon1": "5ZH4H9TX500179J",
    "mon2": "5ZH4H9TX504243B",
    "monitors": "Dual",
    "headphone": false,
    "speaker": false,
    "ipPhone": false,
    "webcam": false,
    "mobileStand": false,
    "whatsapp": false,
    "nextiva": false
   },
   {
    "id": "TS-PC-22",
    "pseudo": "Rihana",
    "shared": false,
    "dept": "Mindhives",
    "type": "Desktop",
    "cpu": "Intel i5 12th Gen",
    "ram": "16 GB",
    "hdd": "480 GB",
    "mon1": "5ZUFH9JX500558A",
    "mon2": "5ZUFH9JX500607N",
    "monitors": "Dual",
    "headphone": true,
    "speaker": false,
    "ipPhone": false,
    "webcam": false,
    "mobileStand": false,
    "whatsapp": false,
    "nextiva": false
   },
   {
    "id": "TS-PC-19",
    "pseudo": "Ray",
    "shared": false,
    "dept": "Mindhives",
    "type": "Desktop",
    "cpu": "Intel i5 12th Gen",
    "ram": "16 GB",
    "hdd": "480 GB",
    "mon1": "5ZHXH9TXA00467T",
    "mon2": "5ZHXH9TX806419R",
    "monitors": "Dual",
    "headphone": true,
    "speaker": false,
    "ipPhone": false,
    "webcam": false,
    "mobileStand": false,
    "whatsapp": false,
    "nextiva": false
   },
   {
    "id": "TS-PC-190",
    "pseudo": "Revin",
    "shared": false,
    "dept": "Mindhives",
    "type": "Desktop",
    "cpu": "Intel i5 12th Gen",
    "ram": "16 GB",
    "hdd": "480 GB",
    "mon1": "0WTLHNCY407681K",
    "mon2": "52UFH9JX300944H",
    "monitors": "Dual",
    "headphone": false,
    "speaker": false,
    "ipPhone": false,
    "webcam": false,
    "mobileStand": false,
    "whatsapp": false,
    "nextiva": false
   },
   {
    "id": "TS-PC-193",
    "pseudo": "Theo",
    "shared": false,
    "dept": "Mindhives",
    "type": "Desktop",
    "cpu": "Intel i7 14th Gen",
    "ram": "16 GB",
    "hdd": "480 GB",
    "mon1": "7DU3H9DYA03047D",
    "mon2": "7DU3H9DL101155K",
    "monitors": "Dual",
    "headphone": false,
    "speaker": false,
    "ipPhone": false,
    "webcam": false,
    "mobileStand": false,
    "whatsapp": false,
    "nextiva": false
   },
   {
    "id": "TS-PC-194",
    "pseudo": "Colt",
    "shared": false,
    "dept": "Mindhives",
    "type": "Desktop",
    "cpu": "Intel i5 12th Gen",
    "ram": "32 GB",
    "hdd": "480 GB & 240 GB",
    "mon1": "7DU3H9DL101127K",
    "mon2": "7DU3H9DL101167D",
    "monitors": "Dual",
    "headphone": false,
    "speaker": false,
    "ipPhone": false,
    "webcam": false,
    "mobileStand": false,
    "whatsapp": false,
    "nextiva": false
   },
   {
    "id": "TS-PC-17",
    "pseudo": "Rylee",
    "shared": false,
    "dept": "Smart Key",
    "type": "Desktop",
    "cpu": "Intel i5 10th Gen",
    "ram": "16 GB",
    "hdd": "480 GB",
    "mon1": "5ZHXH9TXA004389",
    "mon2": "5ZUFH9JX300744N",
    "monitors": "Dual",
    "headphone": true,
    "speaker": false,
    "ipPhone": false,
    "webcam": false,
    "mobileStand": false,
    "whatsapp": false,
    "nextiva": false
   },
   {
    "id": "TS-PC-16",
    "pseudo": "Scott",
    "shared": false,
    "dept": "Smart Key",
    "type": "Desktop",
    "cpu": "Intel i5 12th Gen",
    "ram": "16 GB",
    "hdd": "480 GB",
    "mon1": "5ZHXH9TX804221M",
    "mon2": "5ZHXH9TX804172B",
    "monitors": "Dual",
    "headphone": true,
    "speaker": false,
    "ipPhone": true,
    "webcam": true,
    "mobileStand": false,
    "whatsapp": false,
    "nextiva": false
   },
   {
    "id": "TS-PC-9",
    "pseudo": "Steve Smith",
    "shared": false,
    "dept": "Smart Key",
    "type": "Desktop",
    "cpu": "Intel i5 10th Gen",
    "ram": "16 GB",
    "hdd": "480 GB",
    "mon1": "5ZHXH9TXA01795Y",
    "mon2": "5ZHXH9TX904628P",
    "monitors": "Dual",
    "headphone": true,
    "speaker": false,
    "ipPhone": false,
    "webcam": false,
    "mobileStand": false,
    "whatsapp": false,
    "nextiva": false
   },
   {
    "id": "TS-PC-15",
    "pseudo": "Daryl",
    "shared": false,
    "dept": "Smart Key",
    "type": "Desktop",
    "cpu": "Intel i5 10th Gen",
    "ram": "16 GB",
    "hdd": "480 GB",
    "mon1": "5ZUFH9JX300793W",
    "mon2": "5ZHXH9TX701584H",
    "monitors": "Dual",
    "headphone": true,
    "speaker": false,
    "ipPhone": true,
    "webcam": false,
    "mobileStand": false,
    "whatsapp": false,
    "nextiva": false
   },
   {
    "id": "TS-PC-14",
    "pseudo": "Alex",
    "shared": false,
    "dept": "Smart Key",
    "type": "Desktop",
    "cpu": "Intel i5 10th Gen",
    "ram": "16 GB",
    "hdd": "480 GB",
    "mon1": "5ZUFH9JXT00943T",
    "mon2": "5ZH4H9TX503908F",
    "monitors": "Dual",
    "headphone": true,
    "speaker": false,
    "ipPhone": true,
    "webcam": false,
    "mobileStand": false,
    "whatsapp": false,
    "nextiva": false
   },
   {
    "id": "TS-PC-13",
    "pseudo": "Emily",
    "shared": false,
    "dept": "Smart Key",
    "type": "Desktop",
    "cpu": "Intel i5 11th Gen",
    "ram": "16 GB",
    "hdd": "480 GB",
    "mon1": "5ZUFH9JX300753B",
    "mon2": "5ZH4H9TX504318A",
    "monitors": "Dual",
    "headphone": true,
    "speaker": false,
    "ipPhone": false,
    "webcam": false,
    "mobileStand": false,
    "whatsapp": false,
    "nextiva": false
   },
   {
    "id": "TS-PC-02",
    "pseudo": "Alden",
    "shared": false,
    "dept": "Smart Key",
    "type": "Desktop",
    "cpu": "Intel i5 10th Gen",
    "ram": "16 GB",
    "hdd": "480 GB",
    "mon1": "5ZH4H9TX504199Y",
    "mon2": "5ZH4H9TX503901A",
    "monitors": "Dual",
    "headphone": true,
    "speaker": false,
    "ipPhone": false,
    "webcam": false,
    "mobileStand": false,
    "whatsapp": false,
    "nextiva": false
   },
   {
    "id": "TS-PC-195",
    "pseudo": "Blaze",
    "shared": false,
    "dept": "Smart Key",
    "type": "Desktop",
    "cpu": "Intel i5 10th Gen",
    "ram": "16 GB",
    "hdd": "480 GB",
    "mon1": "5ZHXH9TX605008T",
    "mon2": "7DU3H9DLI0022R",
    "monitors": "Dual",
    "headphone": true,
    "speaker": false,
    "ipPhone": false,
    "webcam": false,
    "mobileStand": false,
    "whatsapp": false,
    "nextiva": false
   },
   {
    "id": "TS-PC-11",
    "pseudo": "John",
    "shared": false,
    "dept": "Smart Key",
    "type": "Desktop",
    "cpu": "Intel i5 10th Gen",
    "ram": "16 GB",
    "hdd": "480 GB",
    "mon1": "4PWLH4TT500721L",
    "mon2": "4PWLH4TW400273W",
    "monitors": "Dual",
    "headphone": true,
    "speaker": false,
    "ipPhone": true,
    "webcam": true,
    "mobileStand": false,
    "whatsapp": false,
    "nextiva": false
   },
   {
    "id": "TS-PC-12",
    "pseudo": "Otis",
    "shared": false,
    "dept": "Smart Key",
    "type": "Desktop",
    "cpu": "Intel i5 10th Gen",
    "ram": "32 GB",
    "hdd": "480 GB",
    "mon1": "5ZH4H9TX500011V",
    "mon2": "0WPLHNCI407632D",
    "monitors": "Dual",
    "headphone": true,
    "speaker": false,
    "ipPhone": true,
    "webcam": false,
    "mobileStand": false,
    "whatsapp": false,
    "nextiva": false
   },
   {
    "id": "TS-PC-196",
    "pseudo": "Olive",
    "shared": false,
    "dept": "Smart Key",
    "type": "Desktop",
    "cpu": "Intel i5 12th Gen",
    "ram": "16 GB",
    "hdd": "480 GB",
    "mon1": "4PWLH4TT100436A",
    "mon2": "4PWLH4TW500439R",
    "monitors": "Dual",
    "headphone": true,
    "speaker": false,
    "ipPhone": false,
    "webcam": false,
    "mobileStand": false,
    "whatsapp": false,
    "nextiva": false
   },
   {
    "id": "TS-PC-04",
    "pseudo": "Rachel",
    "shared": false,
    "dept": "Smart Key",
    "type": "Desktop",
    "cpu": "Intel i5 12th Gen",
    "ram": "16 GB",
    "hdd": "480 GB",
    "mon1": "5ZUFH9DW503240K",
    "mon2": "5ZUFH9DW502735Y",
    "monitors": "Dual",
    "headphone": true,
    "speaker": false,
    "ipPhone": false,
    "webcam": true,
    "mobileStand": false,
    "whatsapp": false,
    "nextiva": false
   },
   {
    "id": "TS-PC-165",
    "pseudo": "Gary",
    "shared": false,
    "dept": "Smart Key",
    "type": "Desktop",
    "cpu": "Intel i5 12th Gen",
    "ram": "16 GB",
    "hdd": "480 GB",
    "mon1": "5ZUFH9DW600576P",
    "mon2": "7DU3H9DL101144B",
    "monitors": "Dual",
    "headphone": true,
    "speaker": false,
    "ipPhone": true,
    "webcam": true,
    "mobileStand": false,
    "whatsapp": false,
    "nextiva": false
   },
   {
    "id": "TS-PC-197",
    "pseudo": "Dave",
    "shared": false,
    "dept": "Smart Key",
    "type": "Desktop",
    "cpu": "Intel i5 12th Gen",
    "ram": "16 GB",
    "hdd": "480 GB",
    "mon1": "0WPLHNCY407524T",
    "mon2": "5ZHX9TX806437D",
    "monitors": "Dual",
    "headphone": true,
    "speaker": false,
    "ipPhone": false,
    "webcam": false,
    "mobileStand": false,
    "whatsapp": false,
    "nextiva": false
   },
   {
    "id": "TS-PC-07",
    "pseudo": "Shaq",
    "shared": false,
    "dept": "Smart Key",
    "type": "Desktop",
    "cpu": "Intel i5 10th Gen",
    "ram": "8 GB",
    "hdd": "240 GB",
    "mon1": "4PWLH4TTA00270D",
    "mon2": "4PWLH4TT500733N",
    "monitors": "Dual",
    "headphone": true,
    "speaker": true,
    "ipPhone": false,
    "webcam": false,
    "mobileStand": false,
    "whatsapp": false,
    "nextiva": false
   },
   {
    "id": "TS-PC-08",
    "pseudo": "Roy",
    "shared": false,
    "dept": "Smart Key",
    "type": "Desktop",
    "cpu": "Intel i5 11th Gen",
    "ram": "16 GB",
    "hdd": "480 GB",
    "mon1": "5ZHX119TX603254T",
    "mon2": "4PWLHUTW400461Z",
    "monitors": "Dual",
    "headphone": true,
    "speaker": false,
    "ipPhone": true,
    "webcam": true,
    "mobileStand": false,
    "whatsapp": false,
    "nextiva": false
   },
   {
    "id": "TS-PC-18",
    "pseudo": "Ricky",
    "shared": false,
    "dept": "Smart Key",
    "type": "Desktop",
    "cpu": "Intel i5 12th Gen",
    "ram": "16 GB",
    "hdd": "480 GB",
    "mon1": "7DU3H9DVA02053F",
    "mon2": "5ZHXH9TX904573X",
    "monitors": "Dual",
    "headphone": true,
    "speaker": false,
    "ipPhone": false,
    "webcam": true,
    "mobileStand": true,
    "whatsapp": false,
    "nextiva": false
   },
   {
    "id": "TS-PC-03",
    "pseudo": "Danny",
    "shared": false,
    "dept": "Smart Key",
    "type": "Desktop",
    "cpu": "Intel i5 9th Gen",
    "ram": "16 GB",
    "hdd": "240 GB",
    "mon1": "4PWLH4TW500382R",
    "mon2": "4PWLH4TW500401K",
    "monitors": "Dual",
    "headphone": true,
    "speaker": false,
    "ipPhone": false,
    "webcam": true,
    "mobileStand": true,
    "whatsapp": false,
    "nextiva": false
   },
   {
    "id": "TS-PC-198",
    "pseudo": "Tia",
    "shared": false,
    "dept": "Watches",
    "type": "Desktop",
    "cpu": "Intel i5 10th Gen",
    "ram": "8 GB",
    "hdd": "240 GB",
    "mon1": "5ZHXH9TX804406F",
    "mon2": "0WPLHNCY407674F",
    "monitors": "Dual",
    "headphone": true,
    "speaker": true,
    "ipPhone": true,
    "webcam": false,
    "mobileStand": false,
    "whatsapp": false,
    "nextiva": false
   },
   {
    "id": "TS-PC-161",
    "pseudo": "Day-Shift PC",
    "shared": true,
    "dept": "Watches",
    "type": "Desktop",
    "cpu": "Intel i5 9th Gen",
    "ram": "16 GB",
    "hdd": "480 GB",
    "mon1": "4PWLH4TW500433M",
    "mon2": "5ZH4H9TX504241K",
    "monitors": "Dual",
    "headphone": true,
    "speaker": true,
    "ipPhone": false,
    "webcam": false,
    "mobileStand": false,
    "whatsapp": false,
    "nextiva": false
   },
   {
    "id": "TS-PC-167",
    "pseudo": "Dexter",
    "shared": false,
    "dept": "Watches",
    "type": "Desktop",
    "cpu": "Intel i5 10th Gen",
    "ram": "16 GB",
    "hdd": "240 GB",
    "mon1": "5ZHXH9TX804213F",
    "mon2": "5ZH4H9TX504325X",
    "monitors": "Dual",
    "headphone": true,
    "speaker": true,
    "ipPhone": false,
    "webcam": false,
    "mobileStand": false,
    "whatsapp": false,
    "nextiva": false
   },
   {
    "id": "TS-PC-166",
    "pseudo": "Addy",
    "shared": false,
    "dept": "Watches",
    "type": "Desktop",
    "cpu": "Intel i5 9th Gen",
    "ram": "8 GB",
    "hdd": "240 GB",
    "mon1": "5ZHXH9TXA00442L",
    "mon2": "5ZH4H9TX504351A",
    "monitors": "Dual",
    "headphone": true,
    "speaker": true,
    "ipPhone": true,
    "webcam": false,
    "mobileStand": true,
    "whatsapp": false,
    "nextiva": false
   },
   {
    "id": "TS-PC-46",
    "pseudo": "Azee",
    "shared": false,
    "dept": "Watches",
    "type": "Desktop",
    "cpu": "Intel i5 9th Gen",
    "ram": "8 GB",
    "hdd": "240 GB",
    "mon1": "7DU3H9DYB01244L",
    "mon2": "7DU3H9DYC01080R",
    "monitors": "Dual",
    "headphone": true,
    "speaker": true,
    "ipPhone": true,
    "webcam": false,
    "mobileStand": false,
    "whatsapp": false,
    "nextiva": false
   },
   {
    "id": "TS-PC-35",
    "pseudo": "Kayra New",
    "shared": false,
    "dept": "Watches",
    "type": "Desktop",
    "cpu": "Intel i5 10th Gen",
    "ram": "16 GB",
    "hdd": "480 GB",
    "mon1": "4PWLH4TTA00346J",
    "mon2": "4PWLH4TW400269M",
    "monitors": "Dual",
    "headphone": true,
    "speaker": true,
    "ipPhone": false,
    "webcam": false,
    "mobileStand": false,
    "whatsapp": false,
    "nextiva": false
   },
   {
    "id": "TS-PC-05",
    "pseudo": "Kayra Old",
    "shared": false,
    "dept": "Watches",
    "type": "Desktop",
    "cpu": "Intel i5 10th Gen",
    "ram": "12 GB",
    "hdd": "240 GB",
    "mon1": "0WPLHLAXB02609V",
    "mon2": "0WPLHNAXB02567F",
    "monitors": "Dual",
    "headphone": true,
    "speaker": true,
    "ipPhone": false,
    "webcam": false,
    "mobileStand": false,
    "whatsapp": false,
    "nextiva": false
   },
   {
    "id": "TS-PC-168",
    "pseudo": "Roman",
    "shared": false,
    "dept": "Watches",
    "type": "Desktop",
    "cpu": "Intel i5 10th Gen",
    "ram": "32 GB",
    "hdd": "480 GB",
    "mon1": "4PWLH4TW400282A",
    "mon2": "4PWLH4TW400271X",
    "monitors": "Dual",
    "headphone": true,
    "speaker": true,
    "ipPhone": true,
    "webcam": true,
    "mobileStand": false,
    "whatsapp": false,
    "nextiva": false
   },
   {
    "id": "TS-PC-36",
    "pseudo": "Kendrick",
    "shared": false,
    "dept": "Watches",
    "type": "Desktop",
    "cpu": "Intel i5 10th Gen",
    "ram": "8 GB",
    "hdd": "240 GB",
    "mon1": "5ZUFH9BW503685K",
    "mon2": "BZUTH4TR400479K",
    "monitors": "Dual",
    "headphone": true,
    "speaker": true,
    "ipPhone": false,
    "webcam": false,
    "mobileStand": true,
    "whatsapp": false,
    "nextiva": false
   },
   {
    "id": "TS-PC-175",
    "pseudo": "David",
    "shared": false,
    "dept": "Watches",
    "type": "Desktop",
    "cpu": "Intel i5 12th Gen",
    "ram": "16 GB",
    "hdd": "480 GB",
    "mon1": "5ZUFH9DW502227H",
    "mon2": "5ZUFH9DW500935Y",
    "monitors": "Dual",
    "headphone": true,
    "speaker": false,
    "ipPhone": false,
    "webcam": false,
    "mobileStand": false,
    "whatsapp": false,
    "nextiva": false
   },
   {
    "id": "TS-PC-06",
    "pseudo": "Roger",
    "shared": false,
    "dept": "Watches",
    "type": "Desktop",
    "cpu": "Intel i5 12th Gen",
    "ram": "16 GB",
    "hdd": "480 GB",
    "mon1": "5ZHXH9TX8037027T",
    "mon2": "5ZHXH9TX806438E",
    "monitors": "Dual",
    "headphone": true,
    "speaker": false,
    "ipPhone": false,
    "webcam": true,
    "mobileStand": false,
    "whatsapp": false,
    "nextiva": false
   },
   {
    "id": "TS-PC-199",
    "pseudo": "Drek",
    "shared": false,
    "dept": "Watches",
    "type": "Desktop",
    "cpu": "Intel i5 12th Gen",
    "ram": "16 GB",
    "hdd": "480 GB",
    "mon1": "5ZHXH9TX803666A",
    "mon2": "5ZHXH9TX806424D",
    "monitors": "Dual",
    "headphone": true,
    "speaker": true,
    "ipPhone": false,
    "webcam": false,
    "mobileStand": false,
    "whatsapp": false,
    "nextiva": false
   },
   {
    "id": "TS-PC-33",
    "pseudo": "Remo",
    "shared": false,
    "dept": "Watches",
    "type": "Desktop",
    "cpu": "Intel i5 10th Gen",
    "ram": "8 GB",
    "hdd": "240 GB",
    "mon1": "4PWLH4TRC00016T",
    "mon2": "5ZHXH9TX806482Z",
    "monitors": "Dual",
    "headphone": true,
    "speaker": true,
    "ipPhone": false,
    "webcam": false,
    "mobileStand": true,
    "whatsapp": false,
    "nextiva": false
   },
   {
    "id": "TS-PC-180",
    "pseudo": "Cyrus",
    "shared": false,
    "dept": "Watches",
    "type": "Desktop",
    "cpu": "Intel i5 12th Gen",
    "ram": "16 GB",
    "hdd": "480 GB",
    "mon1": "7DU3H9DYC01076A",
    "mon2": "5ZHXH9TX603284H",
    "monitors": "Dual",
    "headphone": true,
    "speaker": false,
    "ipPhone": false,
    "webcam": false,
    "mobileStand": false,
    "whatsapp": false,
    "nextiva": false
   },
   {
    "id": "TS-PC-37",
    "pseudo": "Dominic",
    "shared": false,
    "dept": "Watches",
    "type": "Desktop",
    "cpu": "Intel i5 10th Gen",
    "ram": "16 GB",
    "hdd": "480 GB",
    "mon1": "5ZHX49TX803665K",
    "mon2": "5ZHX49TX806444X",
    "monitors": "Dual",
    "headphone": true,
    "speaker": true,
    "ipPhone": false,
    "webcam": false,
    "mobileStand": false,
    "whatsapp": false,
    "nextiva": false
   },
   {
    "id": "TS-PC-25",
    "pseudo": "Day-Shift PC",
    "shared": true,
    "dept": "MIS/IT",
    "type": "Desktop",
    "cpu": "Intel i5 10th Gen",
    "ram": "16 GB",
    "hdd": "480 GB",
    "mon1": "7DU3H9DYA03087T",
    "mon2": "5ZH4H9TX504281X",
    "monitors": "Dual",
    "headphone": false,
    "speaker": false,
    "ipPhone": false,
    "webcam": false,
    "mobileStand": false,
    "whatsapp": false,
    "nextiva": false
   },
   {
    "id": "TS-PC-30",
    "pseudo": "Santosh",
    "shared": false,
    "dept": "MIS/IT",
    "type": "Desktop",
    "cpu": "Intel i5 12th Gen",
    "ram": "24 GB",
    "hdd": "480 GB",
    "mon1": "7DU3H9DYB01284W",
    "mon2": "7DU3H9DYB01278J",
    "monitors": "Dual",
    "headphone": true,
    "speaker": false,
    "ipPhone": false,
    "webcam": false,
    "mobileStand": false,
    "whatsapp": false,
    "nextiva": false
   },
   {
    "id": "TS-PC-48",
    "pseudo": "Sachin",
    "shared": false,
    "dept": "MIS/IT",
    "type": "Desktop",
    "cpu": "Intel i5 10th Gen",
    "ram": "16 GB",
    "hdd": "480 GB",
    "mon1": "5ZH4H9TX504323N",
    "mon2": "4PWLH4TTA00019R",
    "monitors": "Dual",
    "headphone": false,
    "speaker": false,
    "ipPhone": false,
    "webcam": false,
    "mobileStand": false,
    "whatsapp": false,
    "nextiva": false
   },
   {
    "id": "TS-PC-49",
    "pseudo": "Mahendra",
    "shared": false,
    "dept": "MIS/IT",
    "type": "Desktop",
    "cpu": "Intel i5 11th Gen",
    "ram": "16 GB",
    "hdd": "480 GB",
    "mon1": "5ZH4H9TX500064Y",
    "mon2": "4PWLH4TW800109F",
    "monitors": "Dual",
    "headphone": false,
    "speaker": false,
    "ipPhone": false,
    "webcam": false,
    "mobileStand": false,
    "whatsapp": false,
    "nextiva": false
   }
  ];

  window.DEPARTMENTS = DEPARTMENTS;
  window.ASSET_TYPES = ASSET_TYPES;
  window.DEPT_HUE = DEPT_HUE;
  window.ASSETS = ASSETS;
  window.TOTAL_INVENTORY = 184;

  // IT team / system users
  window.USERS = [
    { name: "Santosh", role: "Team Manager", email: "santosh@tasksource.io", since: "2021-03-15", phone: "Ext 100", focus: "Fleet strategy, approvals & vendor management" },
    { name: "Sachin", role: "Team Member", email: "sachin@tasksource.io", since: "2022-07-04", phone: "Ext 104", focus: "Provisioning, repairs & on-site support" },
    { name: "Mahendra", role: "Team Member", email: "mahendra@tasksource.io", since: "2023-01-19", phone: "Ext 106", focus: "Asset intake, audits & peripheral kitting" },
  ];

  // Seed audit history (relative to mid-Jun 2026) — newest first
  window.AUDIT_SEED = [
    { ts: "2026-06-15T09:24:00", actor: "Santosh", action: "edited", tag: "TS-PC-92", subject: "Edward", dept: "Purchase", detail: "RAM updated 8 GB → 16 GB" },
    { ts: "2026-06-15T08:52:00", actor: "Santosh", action: "assigned", tag: "TS-PC-201", subject: "Naomi", dept: "Sales Outbound", detail: "New desktop assigned" },
    { ts: "2026-06-14T17:10:00", actor: "Sachin", action: "repair", tag: "TS-PC-176", subject: "Herry", dept: "Smart Key", detail: "Flagged for repair — monitor flicker" },
    { ts: "2026-06-14T11:38:00", actor: "Santosh", action: "edited", tag: "TS-PC-181", subject: "Denver", dept: "Sales", detail: "Added 2nd monitor — now Dual" },
    { ts: "2026-06-13T15:02:00", actor: "Mahendra", action: "assigned", tag: "TS-PC-157", subject: "Dino", dept: "Watches", detail: "Headphone + speaker added to kit" },
    { ts: "2026-06-12T10:19:00", actor: "Santosh", action: "removed", tag: "TS-PC-066", subject: "Old spare unit", dept: "MIS/IT", detail: "Decommissioned — failed PSU" },
    { ts: "2026-06-12T09:05:00", actor: "Sachin", action: "added", tag: "TS-PC-200", subject: "Stock", dept: "MIS/IT", detail: "New desktop registered to inventory" },
    { ts: "2026-06-11T14:47:00", actor: "Santosh", action: "reassigned", tag: "TS-PC-134", subject: "Atlas → Priya", dept: "Accounts", detail: "Reassigned after role change" },
    { ts: "2026-06-10T16:33:00", actor: "Mahendra", action: "edited", tag: "TS-PC-154", subject: "Philip", dept: "Purchase", detail: "Storage updated 256 GB → 480 GB SSD" },
    { ts: "2026-06-10T09:58:00", actor: "Santosh", action: "assigned", tag: "TS-PC-189", subject: "Micheal", dept: "Surya", detail: "IP phone line provisioned" },
    { ts: "2026-06-09T13:21:00", actor: "Sachin", action: "repair", tag: "TS-PC-039", subject: "James", dept: "Sales", detail: "Returned from repair — keyboard replaced" },
    { ts: "2026-06-08T11:12:00", actor: "Santosh", action: "edited", tag: "TS-PC-158", subject: "Adam", dept: "Sales Outbound", detail: "CPU corrected to Intel i5 12th Gen" },
    { ts: "2026-06-06T15:40:00", actor: "Mahendra", action: "added", tag: "TS-PC-199", subject: "Stock", dept: "MIS/IT", detail: "Bulk intake — 3 units registered" },
    { ts: "2026-06-05T10:04:00", actor: "Santosh", action: "removed", tag: "TS-PC-051", subject: "Damaged unit", dept: "Shipping", detail: "Written off — water damage" },
  ];
})();
