window.ASSET_SEED_DATA = [
 {
  "id": "A001",
  "tag": "TS-PC-134",
  "name": "Sid",
  "dept": "LGD Purchase",
  "type": "Desktop",
  "cpu": null,
  "ram": null,
  "hdd": null,
  "sn1": null,
  "sn2": null,
  "periph": {
   "headphone": true,
   "speaker": true,
   "ipPhone": false,
   "webcam": false,
   "mobileStand": false
  },
  "status": "Assigned",
  "date": "2023-02-18"
 },
 {
  "id": "A002",
  "tag": "TS-PC-01",
  "name": "Jasper",
  "dept": "LGD Purchase",
  "type": "Desktop",
  "cpu": null,
  "ram": null,
  "hdd": null,
  "sn1": null,
  "sn2": null,
  "periph": {
   "headphone": true,
   "speaker": false,
   "ipPhone": false,
   "webcam": false,
   "mobileStand": false
  },
  "status": "Assigned",
  "date": "2023-02-15"
 },
 {
  "id": "A003",
  "tag": "TS-PC-137",
  "name": "Louis",
  "dept": "LGD Purchase",
  "type": "Desktop",
  "cpu": null,
  "ram": null,
  "hdd": null,
  "sn1": null,
  "sn2": null,
  "periph": {
   "headphone": false,
   "speaker": true,
   "ipPhone": false,
   "webcam": false,
   "mobileStand": true
  },
  "status": "Assigned",
  "date": "2023-01-20"
 },
 {
  "id": "A004",
  "tag": "TS-PC-135",
  "name": "Freddy",
  "dept": "LGD Purchase",
  "type": "Desktop",
  "cpu": null,
  "ram": null,
  "hdd": null,
  "sn1": null,
  "sn2": null,
  "periph": {
   "headphone": true,
   "speaker": true,
   "ipPhone": false,
   "webcam": false,
   "mobileStand": true
  },
  "status": "Assigned",
  "date": "2023-02-01"
 },
 {
  "id": "A005",
  "tag": "TS-PC-114",
  "name": "Jim",
  "dept": "LGD Purchase",
  "type": "Desktop",
  "cpu": null,
  "ram": null,
  "hdd": null,
  "sn1": null,
  "sn2": null,
  "periph": {
   "headphone": true,
   "speaker": true,
   "ipPhone": false,
   "webcam": false,
   "mobileStand": false
  },
  "status": "Assigned",
  "date": "2023-02-17"
 },
 {
  "id": "A006",
  "tag": "TS-PC-110",
  "name": "Day Shift (Shared)",
  "dept": "LGD Purchase",
  "type": "Desktop",
  "cpu": null,
  "ram": null,
  "hdd": null,
  "sn1": null,
  "sn2": null,
  "periph": {
   "headphone": true,
   "speaker": false,
   "ipPhone": false,
   "webcam": false,
   "mobileStand": false
  },
  "status": "Assigned",
  "date": "2023-01-17"
 },
 {
  "id": "A007",
  "tag": "TS-PC-139",
  "name": "Justin",
  "dept": "LGD Purchase",
  "type": "Desktop",
  "cpu": null,
  "ram": null,
  "hdd": null,
  "sn1": null,
  "sn2": null,
  "periph": {
   "headphone": true,
   "speaker": false,
   "ipPhone": false,
   "webcam": false,
   "mobileStand": false
  },
  "status": "Assigned",
  "date": "2023-01-15"
 },
 {
  "id": "A008",
  "tag": "TS-PC-133",
  "name": "Kenny",
  "dept": "LGD Purchase",
  "type": "Desktop",
  "cpu": null,
  "ram": null,
  "hdd": null,
  "sn1": null,
  "sn2": null,
  "periph": {
   "headphone": true,
   "speaker": true,
   "ipPhone": false,
   "webcam": false,
   "mobileStand": false
  },
  "status": "Assigned",
  "date": "2023-01-29"
 },
 {
  "id": "A009",
  "tag": "TS-PC-129",
  "name": "Day Shift (Shared)",
  "dept": "LGD Purchase",
  "type": "Desktop",
  "cpu": null,
  "ram": null,
  "hdd": null,
  "sn1": null,
  "sn2": null,
  "periph": {
   "headphone": false,
   "speaker": false,
   "ipPhone": false,
   "webcam": false,
   "mobileStand": false
  },
  "status": "Assigned",
  "date": "2023-02-16"
 },
 {
  "id": "A010",
  "tag": "TS-PC-130",
  "name": "Glenn",
  "dept": "LGD Purchase",
  "type": "Desktop",
  "cpu": null,
  "ram": null,
  "hdd": null,
  "sn1": null,
  "sn2": null,
  "periph": {
   "headphone": true,
   "speaker": true,
   "ipPhone": false,
   "webcam": false,
   "mobileStand": false
  },
  "status": "Assigned",
  "date": "2023-02-16"
 },
 {
  "id": "A011",
  "tag": "TS-PC-131",
  "name": "Joseph",
  "dept": "LGD Purchase",
  "type": "Desktop",
  "cpu": null,
  "ram": null,
  "hdd": null,
  "sn1": null,
  "sn2": null,
  "periph": {
   "headphone": true,
   "speaker": true,
   "ipPhone": false,
   "webcam": false,
   "mobileStand": true
  },
  "status": "Assigned",
  "date": "2023-02-21"
 },
 {
  "id": "A012",
  "tag": "TS-PC-132",
  "name": "Monika",
  "dept": "LGD Purchase",
  "type": "Desktop",
  "cpu": null,
  "ram": null,
  "hdd": null,
  "sn1": null,
  "sn2": null,
  "periph": {
   "headphone": true,
   "speaker": true,
   "ipPhone": false,
   "webcam": false,
   "mobileStand": false
  },
  "status": "Assigned",
  "date": "2023-01-24"
 },
 {
  "id": "A013",
  "tag": "TS-PC-137",
  "name": "Mathew",
  "dept": "LGD Purchase",
  "type": "Desktop",
  "cpu": null,
  "ram": null,
  "hdd": null,
  "sn1": null,
  "sn2": null,
  "periph": {
   "headphone": true,
   "speaker": true,
   "ipPhone": false,
   "webcam": false,
   "mobileStand": true
  },
  "status": "Assigned",
  "date": "2023-01-25"
 },
 {
  "id": "A014",
  "tag": "TS-PC-141",
  "name": "Harvey",
  "dept": "LGD Purchase",
  "type": "Desktop",
  "cpu": null,
  "ram": null,
  "hdd": null,
  "sn1": null,
  "sn2": null,
  "periph": {
   "headphone": true,
   "speaker": false,
   "ipPhone": false,
   "webcam": false,
   "mobileStand": true
  },
  "status": "Assigned",
  "date": "2023-01-31"
 },
 {
  "id": "A015",
  "tag": "TS-PC-127",
  "name": "Bella",
  "dept": "Sales",
  "type": "Desktop",
  "cpu": null,
  "ram": null,
  "hdd": null,
  "sn1": null,
  "sn2": null,
  "periph": {
   "headphone": true,
   "speaker": true,
   "ipPhone": false,
   "webcam": false,
   "mobileStand": true
  },
  "status": "Assigned",
  "date": "2023-02-18"
 },
 {
  "id": "A016",
  "tag": "TS-PC-123",
  "name": "Flora",
  "dept": "Sales",
  "type": "Desktop",
  "cpu": null,
  "ram": null,
  "hdd": null,
  "sn1": null,
  "sn2": null,
  "periph": {
   "headphone": true,
   "speaker": true,
   "ipPhone": false,
   "webcam": false,
   "mobileStand": true
  },
  "status": "Assigned",
  "date": "2023-01-08"
 },
 {
  "id": "A017",
  "tag": "TS-PC-125",
  "name": "Ranjeet Kaka",
  "dept": "Sales",
  "type": "Desktop",
  "cpu": null,
  "ram": null,
  "hdd": null,
  "sn1": null,
  "sn2": null,
  "periph": {
   "headphone": true,
   "speaker": true,
   "ipPhone": false,
   "webcam": false,
   "mobileStand": false
  },
  "status": "Assigned",
  "date": "2023-01-20"
 },
 {
  "id": "A018",
  "tag": "TS-PC-128",
  "name": "Billy",
  "dept": "LGD Purchase",
  "type": "Desktop",
  "cpu": null,
  "ram": null,
  "hdd": null,
  "sn1": null,
  "sn2": null,
  "periph": {
   "headphone": true,
   "speaker": true,
   "ipPhone": false,
   "webcam": false,
   "mobileStand": false
  },
  "status": "Assigned",
  "date": "2023-01-10"
 },
 {
  "id": "A019",
  "tag": "TS-PC-124",
  "name": "Ammy",
  "dept": "LGD Purchase",
  "type": "Desktop",
  "cpu": null,
  "ram": null,
  "hdd": null,
  "sn1": null,
  "sn2": null,
  "periph": {
   "headphone": true,
   "speaker": false,
   "ipPhone": false,
   "webcam": false,
   "mobileStand": false
  },
  "status": "Assigned",
  "date": "2023-02-23"
 },
 {
  "id": "A020",
  "tag": "TS-PC-39",
  "name": "James",
  "dept": "Accounts",
  "type": "Desktop",
  "cpu": null,
  "ram": null,
  "hdd": null,
  "sn1": null,
  "sn2": null,
  "periph": {
   "headphone": false,
   "speaker": false,
   "ipPhone": false,
   "webcam": false,
   "mobileStand": false
  },
  "status": "Assigned",
  "date": "2023-02-09"
 },
 {
  "id": "A021",
  "tag": "TS-PC-181",
  "name": "Denver",
  "dept": "Accounts",
  "type": "Desktop",
  "cpu": null,
  "ram": null,
  "hdd": null,
  "sn1": null,
  "sn2": null,
  "periph": {
   "headphone": false,
   "speaker": false,
   "ipPhone": false,
   "webcam": false,
   "mobileStand": false
  },
  "status": "Assigned",
  "date": "2023-02-14"
 },
 {
  "id": "A022",
  "tag": "TS-PC-157",
  "name": "Dino",
  "dept": "Accounts",
  "type": "Desktop",
  "cpu": null,
  "ram": null,
  "hdd": null,
  "sn1": null,
  "sn2": null,
  "periph": {
   "headphone": false,
   "speaker": false,
   "ipPhone": false,
   "webcam": false,
   "mobileStand": false
  },
  "status": "Assigned",
  "date": "2023-02-05"
 },
 {
  "id": "A023",
  "tag": "TS-PC-154",
  "name": "Philip",
  "dept": "Accounts",
  "type": "Desktop",
  "cpu": null,
  "ram": null,
  "hdd": null,
  "sn1": null,
  "sn2": null,
  "periph": {
   "headphone": false,
   "speaker": false,
   "ipPhone": false,
   "webcam": false,
   "mobileStand": false
  },
  "status": "Assigned",
  "date": "2023-01-23"
 },
 {
  "id": "A024",
  "tag": "TS-PC-176",
  "name": "Herry",
  "dept": "Accounts",
  "type": "Desktop",
  "cpu": null,
  "ram": null,
  "hdd": null,
  "sn1": null,
  "sn2": null,
  "periph": {
   "headphone": false,
   "speaker": false,
   "ipPhone": false,
   "webcam": false,
   "mobileStand": false
  },
  "status": "Assigned",
  "date": "2023-02-10"
 },
 {
  "id": "A025",
  "tag": "TS-PC-189",
  "name": "Micheal",
  "dept": "Accounts",
  "type": "Desktop",
  "cpu": null,
  "ram": null,
  "hdd": null,
  "sn1": null,
  "sn2": null,
  "periph": {
   "headphone": true,
   "speaker": false,
   "ipPhone": true,
   "webcam": false,
   "mobileStand": false
  },
  "status": "Assigned",
  "date": "2023-01-30"
 },
 {
  "id": "A026",
  "tag": "TS-PC-158",
  "name": "Adam",
  "dept": "Accounts",
  "type": "Desktop",
  "cpu": null,
  "ram": null,
  "hdd": null,
  "sn1": null,
  "sn2": null,
  "periph": {
   "headphone": false,
   "speaker": false,
   "ipPhone": true,
   "webcam": false,
   "mobileStand": false
  },
  "status": "Assigned",
  "date": "2023-02-05"
 },
 {
  "id": "A027",
  "tag": "TS-PC-179",
  "name": "Bruce",
  "dept": "Accounts",
  "type": "Desktop",
  "cpu": null,
  "ram": null,
  "hdd": null,
  "sn1": null,
  "sn2": null,
  "periph": {
   "headphone": false,
   "speaker": false,
   "ipPhone": true,
   "webcam": false,
   "mobileStand": false
  },
  "status": "Assigned",
  "date": "2023-01-22"
 },
 {
  "id": "A028",
  "tag": "TS-PC-188",
  "name": "Elena",
  "dept": "Accounts",
  "type": "Desktop",
  "cpu": null,
  "ram": null,
  "hdd": null,
  "sn1": null,
  "sn2": null,
  "periph": {
   "headphone": true,
   "speaker": false,
   "ipPhone": false,
   "webcam": false,
   "mobileStand": false
  },
  "status": "Assigned",
  "date": "2023-02-01"
 },
 {
  "id": "A029",
  "tag": "TS-PC-183",
  "name": "Miller",
  "dept": "Accounts",
  "type": "Desktop",
  "cpu": null,
  "ram": null,
  "hdd": null,
  "sn1": null,
  "sn2": null,
  "periph": {
   "headphone": false,
   "speaker": false,
   "ipPhone": false,
   "webcam": false,
   "mobileStand": false
  },
  "status": "Assigned",
  "date": "2023-02-08"
 },
 {
  "id": "A030",
  "tag": "TS-PC-66",
  "name": "Morgan",
  "dept": "Accounts",
  "type": "Desktop",
  "cpu": null,
  "ram": null,
  "hdd": null,
  "sn1": null,
  "sn2": null,
  "periph": {
   "headphone": false,
   "speaker": false,
   "ipPhone": false,
   "webcam": false,
   "mobileStand": false
  },
  "status": "Assigned",
  "date": "2023-01-23"
 },
 {
  "id": "A031",
  "tag": "TS-PC-153",
  "name": "Max",
  "dept": "Accounts",
  "type": "Desktop",
  "cpu": null,
  "ram": null,
  "hdd": null,
  "sn1": null,
  "sn2": null,
  "periph": {
   "headphone": true,
   "speaker": false,
   "ipPhone": false,
   "webcam": false,
   "mobileStand": false
  },
  "status": "Assigned",
  "date": "2023-02-18"
 },
 {
  "id": "A032",
  "tag": "TS-PC-160",
  "name": "Jordan",
  "dept": "Accounts",
  "type": "Desktop",
  "cpu": null,
  "ram": null,
  "hdd": null,
  "sn1": null,
  "sn2": null,
  "periph": {
   "headphone": false,
   "speaker": false,
   "ipPhone": false,
   "webcam": false,
   "mobileStand": false
  },
  "status": "Assigned",
  "date": "2023-01-19"
 },
 {
  "id": "A033",
  "tag": "TS-PC-184",
  "name": "Sky",
  "dept": "Accounts",
  "type": "Desktop",
  "cpu": null,
  "ram": null,
  "hdd": null,
  "sn1": null,
  "sn2": null,
  "periph": {
   "headphone": true,
   "speaker": false,
   "ipPhone": false,
   "webcam": false,
   "mobileStand": false
  },
  "status": "Assigned",
  "date": "2023-02-19"
 },
 {
  "id": "A034",
  "tag": "TS-PC-156",
  "name": "Charlotte",
  "dept": "Accounts",
  "type": "Desktop",
  "cpu": null,
  "ram": null,
  "hdd": null,
  "sn1": null,
  "sn2": null,
  "periph": {
   "headphone": true,
   "speaker": false,
   "ipPhone": false,
   "webcam": false,
   "mobileStand": false
  },
  "status": "Assigned",
  "date": "2023-01-13"
 },
 {
  "id": "A035",
  "tag": "TS-PC-32",
  "name": "Austin",
  "dept": "Sales Outbound",
  "type": "Desktop",
  "cpu": null,
  "ram": null,
  "hdd": null,
  "sn1": null,
  "sn2": null,
  "periph": {
   "headphone": true,
   "speaker": true,
   "ipPhone": false,
   "webcam": false,
   "mobileStand": false
  },
  "status": "Assigned",
  "date": "2023-02-20"
 },
 {
  "id": "A036",
  "tag": "TS-PC-122",
  "name": "Jeremy",
  "dept": "Sales Outbound",
  "type": "Desktop",
  "cpu": null,
  "ram": null,
  "hdd": null,
  "sn1": null,
  "sn2": null,
  "periph": {
   "headphone": true,
   "speaker": true,
   "ipPhone": false,
   "webcam": false,
   "mobileStand": true
  },
  "status": "Assigned",
  "date": "2023-02-13"
 },
 {
  "id": "A037",
  "tag": "TS-PC-121",
  "name": "Emma",
  "dept": "Sales Outbound",
  "type": "Desktop",
  "cpu": null,
  "ram": null,
  "hdd": null,
  "sn1": null,
  "sn2": null,
  "periph": {
   "headphone": false,
   "speaker": true,
   "ipPhone": false,
   "webcam": false,
   "mobileStand": false
  },
  "status": "Assigned",
  "date": "2023-02-22"
 },
 {
  "id": "A038",
  "tag": "TS-PC-111",
  "name": "Hannah",
  "dept": "Sales Outbound",
  "type": "Desktop",
  "cpu": null,
  "ram": null,
  "hdd": null,
  "sn1": null,
  "sn2": null,
  "periph": {
   "headphone": true,
   "speaker": false,
   "ipPhone": false,
   "webcam": false,
   "mobileStand": true
  },
  "status": "Assigned",
  "date": "2023-02-13"
 },
 {
  "id": "A039",
  "tag": "TS-PC-117",
  "name": "Evelyn",
  "dept": "Sales Outbound",
  "type": "Desktop",
  "cpu": null,
  "ram": null,
  "hdd": null,
  "sn1": null,
  "sn2": null,
  "periph": {
   "headphone": true,
   "speaker": true,
   "ipPhone": false,
   "webcam": false,
   "mobileStand": true
  },
  "status": "Assigned",
  "date": "2023-01-15"
 },
 {
  "id": "A040",
  "tag": "TS-PC-116",
  "name": "Luke",
  "dept": "Sales Outbound",
  "type": "Desktop",
  "cpu": null,
  "ram": null,
  "hdd": null,
  "sn1": null,
  "sn2": null,
  "periph": {
   "headphone": true,
   "speaker": true,
   "ipPhone": false,
   "webcam": false,
   "mobileStand": false
  },
  "status": "Assigned",
  "date": "2023-02-13"
 },
 {
  "id": "A041",
  "tag": "TS-PC-118",
  "name": "Faith",
  "dept": "Sales Outbound",
  "type": "Desktop",
  "cpu": null,
  "ram": null,
  "hdd": null,
  "sn1": null,
  "sn2": null,
  "periph": {
   "headphone": true,
   "speaker": true,
   "ipPhone": false,
   "webcam": false,
   "mobileStand": false
  },
  "status": "Assigned",
  "date": "2023-02-09"
 },
 {
  "id": "A042",
  "tag": "TS-PC-119",
  "name": "Hope",
  "dept": "Sales Outbound",
  "type": "Desktop",
  "cpu": null,
  "ram": null,
  "hdd": null,
  "sn1": null,
  "sn2": null,
  "periph": {
   "headphone": true,
   "speaker": false,
   "ipPhone": false,
   "webcam": false,
   "mobileStand": false
  },
  "status": "Assigned",
  "date": "2023-02-14"
 },
 {
  "id": "A043",
  "tag": "TS-PC-104",
  "name": "Jayden",
  "dept": "Sales",
  "type": "Desktop",
  "cpu": null,
  "ram": null,
  "hdd": null,
  "sn1": null,
  "sn2": null,
  "periph": {
   "headphone": true,
   "speaker": true,
   "ipPhone": false,
   "webcam": false,
   "mobileStand": false
  },
  "status": "Assigned",
  "date": "2023-01-26"
 },
 {
  "id": "A044",
  "tag": "TS-PC-99",
  "name": "Noa",
  "dept": "Sales",
  "type": "Desktop",
  "cpu": null,
  "ram": null,
  "hdd": null,
  "sn1": null,
  "sn2": null,
  "periph": {
   "headphone": true,
   "speaker": true,
   "ipPhone": false,
   "webcam": false,
   "mobileStand": false
  },
  "status": "Assigned",
  "date": "2023-02-25"
 },
 {
  "id": "A045",
  "tag": "TS-PC-100",
  "name": "Skyler",
  "dept": "Sales",
  "type": "Desktop",
  "cpu": null,
  "ram": null,
  "hdd": null,
  "sn1": null,
  "sn2": null,
  "periph": {
   "headphone": true,
   "speaker": true,
   "ipPhone": false,
   "webcam": false,
   "mobileStand": false
  },
  "status": "Assigned",
  "date": "2023-02-17"
 },
 {
  "id": "A046",
  "tag": "TS-PC-102",
  "name": "Zoe",
  "dept": "Sales",
  "type": "Desktop",
  "cpu": null,
  "ram": null,
  "hdd": null,
  "sn1": null,
  "sn2": null,
  "periph": {
   "headphone": true,
   "speaker": true,
   "ipPhone": false,
   "webcam": false,
   "mobileStand": true
  },
  "status": "Assigned",
  "date": "2023-02-17"
 },
 {
  "id": "A047",
  "tag": "TS-PC-98",
  "name": "Walter",
  "dept": "Sales",
  "type": "Desktop",
  "cpu": null,
  "ram": null,
  "hdd": null,
  "sn1": null,
  "sn2": null,
  "periph": {
   "headphone": true,
   "speaker": true,
   "ipPhone": false,
   "webcam": false,
   "mobileStand": true
  },
  "status": "Assigned",
  "date": "2023-02-22"
 },
 {
  "id": "A048",
  "tag": "TS-PC-143",
  "name": "Stefan",
  "dept": "Sales",
  "type": "Desktop",
  "cpu": null,
  "ram": null,
  "hdd": null,
  "sn1": null,
  "sn2": null,
  "periph": {
   "headphone": true,
   "speaker": true,
   "ipPhone": false,
   "webcam": false,
   "mobileStand": true
  },
  "status": "Assigned",
  "date": "2023-01-25"
 },
 {
  "id": "A049",
  "tag": "TS-PC-103",
  "name": "Gabriel",
  "dept": "Sales",
  "type": "Desktop",
  "cpu": null,
  "ram": null,
  "hdd": null,
  "sn1": null,
  "sn2": null,
  "periph": {
   "headphone": true,
   "speaker": false,
   "ipPhone": false,
   "webcam": false,
   "mobileStand": true
  },
  "status": "Assigned",
  "date": "2023-01-10"
 },
 {
  "id": "A050",
  "tag": "TS-PC-109",
  "name": "Ashley",
  "dept": "Sales",
  "type": "Desktop",
  "cpu": null,
  "ram": null,
  "hdd": null,
  "sn1": null,
  "sn2": null,
  "periph": {
   "headphone": true,
   "speaker": true,
   "ipPhone": false,
   "webcam": false,
   "mobileStand": true
  },
  "status": "Assigned",
  "date": "2023-01-25"
 },
 {
  "id": "A051",
  "tag": "TS-PC-106",
  "name": "Lisa",
  "dept": "Sales",
  "type": "Desktop",
  "cpu": null,
  "ram": null,
  "hdd": null,
  "sn1": null,
  "sn2": null,
  "periph": {
   "headphone": true,
   "speaker": true,
   "ipPhone": false,
   "webcam": false,
   "mobileStand": false
  },
  "status": "Assigned",
  "date": "2023-02-03"
 },
 {
  "id": "A052",
  "tag": "TS-PC-108",
  "name": "Renee",
  "dept": "Sales",
  "type": "Desktop",
  "cpu": null,
  "ram": null,
  "hdd": null,
  "sn1": null,
  "sn2": null,
  "periph": {
   "headphone": true,
   "speaker": false,
   "ipPhone": false,
   "webcam": false,
   "mobileStand": false
  },
  "status": "Assigned",
  "date": "2023-01-20"
 },
 {
  "id": "A053",
  "tag": "TS-PC-113",
  "name": "Xavier",
  "dept": "Sales",
  "type": "Desktop",
  "cpu": null,
  "ram": null,
  "hdd": null,
  "sn1": null,
  "sn2": null,
  "periph": {
   "headphone": true,
   "speaker": true,
   "ipPhone": false,
   "webcam": false,
   "mobileStand": false
  },
  "status": "Assigned",
  "date": "2023-02-09"
 },
 {
  "id": "A054",
  "tag": "TS-PC-185",
  "name": "Marshall",
  "dept": "Sales",
  "type": "Desktop",
  "cpu": null,
  "ram": null,
  "hdd": null,
  "sn1": null,
  "sn2": null,
  "periph": {
   "headphone": true,
   "speaker": true,
   "ipPhone": false,
   "webcam": false,
   "mobileStand": false
  },
  "status": "Assigned",
  "date": "2023-01-13"
 },
 {
  "id": "A055",
  "tag": "TS-PC-115",
  "name": "Elsa",
  "dept": "Sales",
  "type": "Desktop",
  "cpu": null,
  "ram": null,
  "hdd": null,
  "sn1": null,
  "sn2": null,
  "periph": {
   "headphone": true,
   "speaker": true,
   "ipPhone": false,
   "webcam": false,
   "mobileStand": false
  },
  "status": "Assigned",
  "date": "2023-02-13"
 },
 {
  "id": "A056",
  "tag": "TS-PC-112",
  "name": "Robin",
  "dept": "Sales",
  "type": "Desktop",
  "cpu": null,
  "ram": null,
  "hdd": null,
  "sn1": null,
  "sn2": null,
  "periph": {
   "headphone": true,
   "speaker": true,
   "ipPhone": false,
   "webcam": false,
   "mobileStand": false
  },
  "status": "Assigned",
  "date": "2023-01-28"
 },
 {
  "id": "A057",
  "tag": "TS-PC-101",
  "name": "River",
  "dept": "Sales",
  "type": "Desktop",
  "cpu": null,
  "ram": null,
  "hdd": null,
  "sn1": null,
  "sn2": null,
  "periph": {
   "headphone": true,
   "speaker": true,
   "ipPhone": false,
   "webcam": false,
   "mobileStand": false
  },
  "status": "Assigned",
  "date": "2023-02-16"
 },
 {
  "id": "A058",
  "tag": "TS-PC-140",
  "name": "Rebecca",
  "dept": "Sales",
  "type": "Desktop",
  "cpu": null,
  "ram": null,
  "hdd": null,
  "sn1": null,
  "sn2": null,
  "periph": {
   "headphone": true,
   "speaker": true,
   "ipPhone": false,
   "webcam": false,
   "mobileStand": false
  },
  "status": "Assigned",
  "date": "2023-01-29"
 },
 {
  "id": "A059",
  "tag": "TS-PC-42",
  "name": "Arnold",
  "dept": "Credit",
  "type": "Desktop",
  "cpu": null,
  "ram": null,
  "hdd": null,
  "sn1": null,
  "sn2": null,
  "periph": {
   "headphone": false,
   "speaker": true,
   "ipPhone": true,
   "webcam": false,
   "mobileStand": false
  },
  "status": "Assigned",
  "date": "2023-01-30"
 },
 {
  "id": "A060",
  "tag": "TS-PC-186",
  "name": "Amanda",
  "dept": "Credit",
  "type": "Desktop",
  "cpu": null,
  "ram": null,
  "hdd": null,
  "sn1": null,
  "sn2": null,
  "periph": {
   "headphone": true,
   "speaker": false,
   "ipPhone": true,
   "webcam": false,
   "mobileStand": false
  },
  "status": "Assigned",
  "date": "2023-02-15"
 },
 {
  "id": "A061",
  "tag": "TS-PC-44",
  "name": "Maverick",
  "dept": "Credit",
  "type": "Desktop",
  "cpu": null,
  "ram": null,
  "hdd": null,
  "sn1": null,
  "sn2": null,
  "periph": {
   "headphone": true,
   "speaker": true,
   "ipPhone": false,
   "webcam": false,
   "mobileStand": true
  },
  "status": "Assigned",
  "date": "2023-02-12"
 },
 {
  "id": "A062",
  "tag": "TS-PC-40",
  "name": "Russel",
  "dept": "Credit",
  "type": "Desktop",
  "cpu": null,
  "ram": null,
  "hdd": null,
  "sn1": null,
  "sn2": null,
  "periph": {
   "headphone": true,
   "speaker": false,
   "ipPhone": true,
   "webcam": false,
   "mobileStand": false
  },
  "status": "Assigned",
  "date": "2023-02-14"
 },
 {
  "id": "A063",
  "tag": "TS-PC-38",
  "name": null,
  "dept": "Credit",
  "type": "Desktop",
  "cpu": null,
  "ram": null,
  "hdd": null,
  "sn1": null,
  "sn2": null,
  "periph": {
   "headphone": false,
   "speaker": false,
   "ipPhone": false,
   "webcam": false,
   "mobileStand": false
  },
  "status": "Available",
  "date": null
 },
 {
  "id": "A064",
  "tag": "TS-PC-187",
  "name": "Clara",
  "dept": "Credit",
  "type": "Desktop",
  "cpu": null,
  "ram": null,
  "hdd": null,
  "sn1": null,
  "sn2": null,
  "periph": {
   "headphone": true,
   "speaker": false,
   "ipPhone": false,
   "webcam": false,
   "mobileStand": false
  },
  "status": "Assigned",
  "date": "2023-01-21"
 },
 {
  "id": "A065",
  "tag": "TS-PC-150",
  "name": "Arthur",
  "dept": "Cheques",
  "type": "Desktop",
  "cpu": null,
  "ram": null,
  "hdd": null,
  "sn1": null,
  "sn2": null,
  "periph": {
   "headphone": true,
   "speaker": false,
   "ipPhone": false,
   "webcam": false,
   "mobileStand": false
  },
  "status": "Assigned",
  "date": "2023-02-06"
 },
 {
  "id": "A066",
  "tag": "TS-PC-34",
  "name": "Amanda",
  "dept": "Cheques",
  "type": "Desktop",
  "cpu": null,
  "ram": null,
  "hdd": null,
  "sn1": null,
  "sn2": null,
  "periph": {
   "headphone": false,
   "speaker": false,
   "ipPhone": false,
   "webcam": false,
   "mobileStand": false
  },
  "status": "Assigned",
  "date": "2023-02-10"
 },
 {
  "id": "A067",
  "tag": "TS-PC-27",
  "name": "Ash",
  "dept": "Cheques",
  "type": "Desktop",
  "cpu": null,
  "ram": null,
  "hdd": null,
  "sn1": null,
  "sn2": null,
  "periph": {
   "headphone": true,
   "speaker": false,
   "ipPhone": false,
   "webcam": false,
   "mobileStand": false
  },
  "status": "Assigned",
  "date": "2023-02-22"
 },
 {
  "id": "A068",
  "tag": "TS-PC-41",
  "name": "Alec",
  "dept": "Cheques",
  "type": "Desktop",
  "cpu": null,
  "ram": null,
  "hdd": null,
  "sn1": null,
  "sn2": null,
  "periph": {
   "headphone": false,
   "speaker": false,
   "ipPhone": false,
   "webcam": false,
   "mobileStand": false
  },
  "status": "Assigned",
  "date": "2023-01-30"
 },
 {
  "id": "A069",
  "tag": "TS-PC-159",
  "name": "Alfred",
  "dept": "Cheques",
  "type": "Desktop",
  "cpu": null,
  "ram": null,
  "hdd": null,
  "sn1": null,
  "sn2": null,
  "periph": {
   "headphone": false,
   "speaker": false,
   "ipPhone": true,
   "webcam": false,
   "mobileStand": false
  },
  "status": "Assigned",
  "date": "2023-01-20"
 },
 {
  "id": "A070",
  "tag": "TS-PC-92",
  "name": "Edward",
  "dept": "Purchase",
  "type": "Desktop",
  "cpu": null,
  "ram": null,
  "hdd": null,
  "sn1": null,
  "sn2": null,
  "periph": {
   "headphone": true,
   "speaker": true,
   "ipPhone": false,
   "webcam": false,
   "mobileStand": false
  },
  "status": "Assigned",
  "date": "2023-01-26"
 },
 {
  "id": "A071",
  "tag": "TS-PC-93",
  "name": "Simon",
  "dept": "Purchase",
  "type": "Desktop",
  "cpu": null,
  "ram": null,
  "hdd": null,
  "sn1": null,
  "sn2": null,
  "periph": {
   "headphone": true,
   "speaker": false,
   "ipPhone": true,
   "webcam": false,
   "mobileStand": true
  },
  "status": "Assigned",
  "date": "2023-02-19"
 },
 {
  "id": "A072",
  "tag": "TS-PC-94",
  "name": "Hazel",
  "dept": "Purchase",
  "type": "Desktop",
  "cpu": null,
  "ram": null,
  "hdd": null,
  "sn1": null,
  "sn2": null,
  "periph": {
   "headphone": true,
   "speaker": false,
   "ipPhone": false,
   "webcam": false,
   "mobileStand": false
  },
  "status": "Assigned",
  "date": "2023-01-10"
 },
 {
  "id": "A073",
  "tag": "TS-PC-96",
  "name": "Jennifier",
  "dept": "Purchase",
  "type": "Desktop",
  "cpu": null,
  "ram": null,
  "hdd": null,
  "sn1": null,
  "sn2": null,
  "periph": {
   "headphone": false,
   "speaker": true,
   "ipPhone": false,
   "webcam": false,
   "mobileStand": false
  },
  "status": "Assigned",
  "date": "2023-01-27"
 },
 {
  "id": "A074",
  "tag": "TS-PC-95",
  "name": "Sam",
  "dept": "Purchase",
  "type": "Desktop",
  "cpu": null,
  "ram": null,
  "hdd": null,
  "sn1": null,
  "sn2": null,
  "periph": {
   "headphone": false,
   "speaker": true,
   "ipPhone": true,
   "webcam": false,
   "mobileStand": false
  },
  "status": "Assigned",
  "date": "2023-02-25"
 },
 {
  "id": "A075",
  "tag": "TS-PC-177",
  "name": "Finn",
  "dept": "Purchase",
  "type": "Desktop",
  "cpu": null,
  "ram": null,
  "hdd": null,
  "sn1": null,
  "sn2": null,
  "periph": {
   "headphone": false,
   "speaker": false,
   "ipPhone": true,
   "webcam": false,
   "mobileStand": false
  },
  "status": "Assigned",
  "date": "2023-02-25"
 },
 {
  "id": "A076",
  "tag": "TS-PC-91",
  "name": "Evan",
  "dept": "Purchase",
  "type": "Desktop",
  "cpu": null,
  "ram": null,
  "hdd": null,
  "sn1": null,
  "sn2": null,
  "periph": {
   "headphone": false,
   "speaker": false,
   "ipPhone": true,
   "webcam": false,
   "mobileStand": false
  },
  "status": "Assigned",
  "date": "2023-01-31"
 },
 {
  "id": "A077",
  "tag": "TS-PC-90",
  "name": "Nelson",
  "dept": "Purchase",
  "type": "Desktop",
  "cpu": null,
  "ram": null,
  "hdd": null,
  "sn1": null,
  "sn2": null,
  "periph": {
   "headphone": false,
   "speaker": false,
   "ipPhone": false,
   "webcam": false,
   "mobileStand": false
  },
  "status": "Assigned",
  "date": "2023-02-07"
 },
 {
  "id": "A078",
  "tag": "TS-PC-89",
  "name": "Logan",
  "dept": "Purchase",
  "type": "Desktop",
  "cpu": null,
  "ram": null,
  "hdd": null,
  "sn1": null,
  "sn2": null,
  "periph": {
   "headphone": false,
   "speaker": false,
   "ipPhone": true,
   "webcam": false,
   "mobileStand": true
  },
  "status": "Assigned",
  "date": "2023-02-10"
 },
 {
  "id": "A079",
  "tag": "TS-PC-88",
  "name": "Thomas",
  "dept": "Shipping",
  "type": "Desktop",
  "cpu": null,
  "ram": null,
  "hdd": null,
  "sn1": null,
  "sn2": null,
  "periph": {
   "headphone": true,
   "speaker": false,
   "ipPhone": true,
   "webcam": false,
   "mobileStand": false
  },
  "status": "Assigned",
  "date": "2023-01-24"
 },
 {
  "id": "A080",
  "tag": "TS-PC-87",
  "name": "Richard",
  "dept": "Shipping",
  "type": "Desktop",
  "cpu": null,
  "ram": null,
  "hdd": null,
  "sn1": null,
  "sn2": null,
  "periph": {
   "headphone": true,
   "speaker": false,
   "ipPhone": false,
   "webcam": false,
   "mobileStand": false
  },
  "status": "Assigned",
  "date": "2023-02-08"
 },
 {
  "id": "A081",
  "tag": "TS-PC-182",
  "name": "Alden",
  "dept": "Sales",
  "type": "Desktop",
  "cpu": null,
  "ram": null,
  "hdd": null,
  "sn1": null,
  "sn2": null,
  "periph": {
   "headphone": true,
   "speaker": false,
   "ipPhone": false,
   "webcam": false,
   "mobileStand": false
  },
  "status": "Assigned",
  "date": "2023-01-20"
 },
 {
  "id": "A082",
  "tag": "TS-PC-86",
  "name": "Mike",
  "dept": "Shipping",
  "type": "Desktop",
  "cpu": null,
  "ram": null,
  "hdd": null,
  "sn1": null,
  "sn2": null,
  "periph": {
   "headphone": true,
   "speaker": false,
   "ipPhone": false,
   "webcam": false,
   "mobileStand": false
  },
  "status": "Assigned",
  "date": "2023-01-23"
 },
 {
  "id": "A083",
  "tag": "TS-PC-80",
  "name": "Willium",
  "dept": "Shipping",
  "type": "Desktop",
  "cpu": null,
  "ram": null,
  "hdd": null,
  "sn1": null,
  "sn2": null,
  "periph": {
   "headphone": true,
   "speaker": true,
   "ipPhone": true,
   "webcam": false,
   "mobileStand": false
  },
  "status": "Assigned",
  "date": "2023-02-08"
 },
 {
  "id": "A084",
  "tag": "TS-PC-81",
  "name": "Joy",
  "dept": "Shipping",
  "type": "Desktop",
  "cpu": null,
  "ram": null,
  "hdd": null,
  "sn1": null,
  "sn2": null,
  "periph": {
   "headphone": true,
   "speaker": true,
   "ipPhone": false,
   "webcam": false,
   "mobileStand": false
  },
  "status": "Assigned",
  "date": "2023-02-24"
 },
 {
  "id": "A085",
  "tag": "TS-PC-82",
  "name": "Broke",
  "dept": "Shipping",
  "type": "Desktop",
  "cpu": null,
  "ram": null,
  "hdd": null,
  "sn1": null,
  "sn2": null,
  "periph": {
   "headphone": true,
   "speaker": false,
   "ipPhone": false,
   "webcam": false,
   "mobileStand": true
  },
  "status": "Assigned",
  "date": "2023-01-19"
 },
 {
  "id": "A086",
  "tag": "TS-PC-173",
  "name": "Tony",
  "dept": "Purchase",
  "type": "Desktop",
  "cpu": null,
  "ram": null,
  "hdd": null,
  "sn1": null,
  "sn2": null,
  "periph": {
   "headphone": false,
   "speaker": false,
   "ipPhone": false,
   "webcam": false,
   "mobileStand": false
  },
  "status": "Assigned",
  "date": "2023-02-24"
 },
 {
  "id": "A087",
  "tag": "TS-PC-84",
  "name": "Wattson",
  "dept": "Purchase",
  "type": "Desktop",
  "cpu": null,
  "ram": null,
  "hdd": null,
  "sn1": null,
  "sn2": null,
  "periph": {
   "headphone": true,
   "speaker": false,
   "ipPhone": true,
   "webcam": false,
   "mobileStand": false
  },
  "status": "Assigned",
  "date": "2023-02-21"
 },
 {
  "id": "A088",
  "tag": "TS-PC-85",
  "name": "Annie",
  "dept": "Purchase",
  "type": "Desktop",
  "cpu": null,
  "ram": null,
  "hdd": null,
  "sn1": null,
  "sn2": null,
  "periph": {
   "headphone": true,
   "speaker": false,
   "ipPhone": false,
   "webcam": false,
   "mobileStand": false
  },
  "status": "Assigned",
  "date": "2023-02-19"
 },
 {
  "id": "A089",
  "tag": "TS-PC-79",
  "name": "Gagan Jat",
  "dept": "Buying",
  "type": "Desktop",
  "cpu": null,
  "ram": null,
  "hdd": null,
  "sn1": null,
  "sn2": null,
  "periph": {
   "headphone": false,
   "speaker": true,
   "ipPhone": false,
   "webcam": false,
   "mobileStand": false
  },
  "status": "Assigned",
  "date": "2023-01-17"
 },
 {
  "id": "A090",
  "tag": "TS-PC-78",
  "name": "Zion",
  "dept": "Buying",
  "type": "Desktop",
  "cpu": null,
  "ram": null,
  "hdd": null,
  "sn1": null,
  "sn2": null,
  "periph": {
   "headphone": true,
   "speaker": false,
   "ipPhone": false,
   "webcam": true,
   "mobileStand": false
  },
  "status": "Assigned",
  "date": "2023-01-13"
 },
 {
  "id": "A091",
  "tag": "TS-PC-77",
  "name": null,
  "dept": "Shared Pool",
  "type": "Desktop",
  "cpu": null,
  "ram": null,
  "hdd": null,
  "sn1": null,
  "sn2": null,
  "periph": {
   "headphone": false,
   "speaker": false,
   "ipPhone": false,
   "webcam": false,
   "mobileStand": false
  },
  "status": "Available",
  "date": null
 },
 {
  "id": "A092",
  "tag": "TS-PC-76",
  "name": "Rio New",
  "dept": "Surya",
  "type": "Desktop",
  "cpu": null,
  "ram": null,
  "hdd": null,
  "sn1": null,
  "sn2": null,
  "periph": {
   "headphone": false,
   "speaker": false,
   "ipPhone": false,
   "webcam": false,
   "mobileStand": false
  },
  "status": "Assigned",
  "date": "2023-01-13"
 },
 {
  "id": "A093",
  "tag": "TS-PC-75",
  "name": "Martine",
  "dept": "Surya",
  "type": "Desktop",
  "cpu": null,
  "ram": null,
  "hdd": null,
  "sn1": null,
  "sn2": null,
  "periph": {
   "headphone": false,
   "speaker": false,
   "ipPhone": true,
   "webcam": false,
   "mobileStand": false
  },
  "status": "Assigned",
  "date": "2023-01-30"
 },
 {
  "id": "A094",
  "tag": "TS-PC-74",
  "name": "Ethan",
  "dept": "Surya",
  "type": "Desktop",
  "cpu": null,
  "ram": null,
  "hdd": null,
  "sn1": null,
  "sn2": null,
  "periph": {
   "headphone": false,
   "speaker": false,
   "ipPhone": true,
   "webcam": false,
   "mobileStand": false
  },
  "status": "Assigned",
  "date": "2023-01-20"
 },
 {
  "id": "A095",
  "tag": "TS-PC-68",
  "name": "Davis",
  "dept": "Surya",
  "type": "Desktop",
  "cpu": null,
  "ram": null,
  "hdd": null,
  "sn1": null,
  "sn2": null,
  "periph": {
   "headphone": false,
   "speaker": false,
   "ipPhone": true,
   "webcam": false,
   "mobileStand": false
  },
  "status": "Assigned",
  "date": "2023-02-09"
 },
 {
  "id": "A096",
  "tag": "TS-PC-69",
  "name": "Rio Old",
  "dept": "Surya",
  "type": "Desktop",
  "cpu": null,
  "ram": null,
  "hdd": null,
  "sn1": null,
  "sn2": null,
  "periph": {
   "headphone": false,
   "speaker": false,
   "ipPhone": false,
   "webcam": false,
   "mobileStand": true
  },
  "status": "Assigned",
  "date": "2023-02-21"
 },
 {
  "id": "A097",
  "tag": "TS-PC-71",
  "name": "Day Shift (Shared)",
  "dept": "Surya",
  "type": "Desktop",
  "cpu": null,
  "ram": null,
  "hdd": null,
  "sn1": null,
  "sn2": null,
  "periph": {
   "headphone": false,
   "speaker": false,
   "ipPhone": false,
   "webcam": false,
   "mobileStand": false
  },
  "status": "Assigned",
  "date": "2023-02-11"
 },
 {
  "id": "A098",
  "tag": "TS-PC-70",
  "name": "Day Shift (Shared)",
  "dept": "Surya",
  "type": "Desktop",
  "cpu": null,
  "ram": null,
  "hdd": null,
  "sn1": null,
  "sn2": null,
  "periph": {
   "headphone": false,
   "speaker": false,
   "ipPhone": false,
   "webcam": false,
   "mobileStand": false
  },
  "status": "Assigned",
  "date": "2023-01-26"
 },
 {
  "id": "A099",
  "tag": "TS-PC-72",
  "name": "Day Shift (Shared)",
  "dept": "Surya",
  "type": "Desktop",
  "cpu": null,
  "ram": null,
  "hdd": null,
  "sn1": null,
  "sn2": null,
  "periph": {
   "headphone": false,
   "speaker": false,
   "ipPhone": false,
   "webcam": false,
   "mobileStand": false
  },
  "status": "Assigned",
  "date": "2023-02-26"
 },
 {
  "id": "A100",
  "tag": "TS-PC-61",
  "name": "Ella",
  "dept": "Payments",
  "type": "Desktop",
  "cpu": null,
  "ram": null,
  "hdd": null,
  "sn1": null,
  "sn2": null,
  "periph": {
   "headphone": true,
   "speaker": false,
   "ipPhone": false,
   "webcam": false,
   "mobileStand": false
  },
  "status": "Assigned",
  "date": "2023-02-19"
 },
 {
  "id": "A101",
  "tag": "TS-PC-64",
  "name": "Day Shift (Shared)",
  "dept": "Payments",
  "type": "Desktop",
  "cpu": null,
  "ram": null,
  "hdd": null,
  "sn1": null,
  "sn2": null,
  "periph": {
   "headphone": true,
   "speaker": false,
   "ipPhone": false,
   "webcam": false,
   "mobileStand": false
  },
  "status": "Assigned",
  "date": "2023-02-19"
 },
 {
  "id": "A102",
  "tag": "TS-PC-54",
  "name": "Rose",
  "dept": "Payments",
  "type": "Desktop",
  "cpu": null,
  "ram": null,
  "hdd": null,
  "sn1": null,
  "sn2": null,
  "periph": {
   "headphone": true,
   "speaker": true,
   "ipPhone": false,
   "webcam": false,
   "mobileStand": false
  },
  "status": "Assigned",
  "date": "2023-02-10"
 },
 {
  "id": "A103",
  "tag": "TS-PC-53",
  "name": "Erik",
  "dept": "Payments",
  "type": "Desktop",
  "cpu": null,
  "ram": null,
  "hdd": null,
  "sn1": null,
  "sn2": null,
  "periph": {
   "headphone": true,
   "speaker": true,
   "ipPhone": false,
   "webcam": false,
   "mobileStand": false
  },
  "status": "Assigned",
  "date": "2023-02-10"
 },
 {
  "id": "A104",
  "tag": "TS-PC-200",
  "name": "Day Shift (Shared)",
  "dept": "Payments",
  "type": "Desktop",
  "cpu": null,
  "ram": null,
  "hdd": null,
  "sn1": null,
  "sn2": null,
  "periph": {
   "headphone": true,
   "speaker": false,
   "ipPhone": false,
   "webcam": false,
   "mobileStand": false
  },
  "status": "Assigned",
  "date": "2023-01-19"
 },
 {
  "id": "A105",
  "tag": "TS-PC-172",
  "name": "Marcus",
  "dept": "Payments",
  "type": "Desktop",
  "cpu": null,
  "ram": null,
  "hdd": null,
  "sn1": null,
  "sn2": null,
  "periph": {
   "headphone": true,
   "speaker": false,
   "ipPhone": false,
   "webcam": false,
   "mobileStand": false
  },
  "status": "Assigned",
  "date": "2023-02-08"
 },
 {
  "id": "A106",
  "tag": "TS-PC-62",
  "name": "Aron",
  "dept": "Payments",
  "type": "Desktop",
  "cpu": null,
  "ram": null,
  "hdd": null,
  "sn1": null,
  "sn2": null,
  "periph": {
   "headphone": true,
   "speaker": false,
   "ipPhone": true,
   "webcam": true,
   "mobileStand": false
  },
  "status": "Assigned",
  "date": "2023-02-20"
 },
 {
  "id": "A107",
  "tag": "TS-PC-56",
  "name": "Asher",
  "dept": "Payments",
  "type": "Desktop",
  "cpu": "Core i5 10th Gen",
  "ram": "16 GB",
  "hdd": "240 GB",
  "sn1": "5ZH4H9TX503946L",
  "sn2": "5ZUFH90W600578B",
  "periph": {
   "headphone": true,
   "speaker": true,
   "ipPhone": false,
   "webcam": false,
   "mobileStand": false
  },
  "status": "Assigned",
  "date": "2023-02-18"
 },
 {
  "id": "A108",
  "tag": "TS-PC-57",
  "name": "Nora",
  "dept": "Payments",
  "type": "Desktop",
  "cpu": "Core i5 10th Gen",
  "ram": "16 GB",
  "hdd": "240 GB",
  "sn1": "5DNEH4TT802039F",
  "sn2": "BZUTH4TR401567Y",
  "periph": {
   "headphone": true,
   "speaker": true,
   "ipPhone": false,
   "webcam": false,
   "mobileStand": false
  },
  "status": "Assigned",
  "date": "2023-02-11"
 },
 {
  "id": "A109",
  "tag": "TS-PC-138",
  "name": "Lily",
  "dept": "Payments",
  "type": "Desktop",
  "cpu": "Core i5 10th Gen",
  "ram": "16 GB",
  "hdd": "480 GB",
  "sn1": "4PWLHTW400286F",
  "sn2": "4PWLH4TT402442Y",
  "periph": {
   "headphone": true,
   "speaker": true,
   "ipPhone": false,
   "webcam": false,
   "mobileStand": false
  },
  "status": "Assigned",
  "date": "2023-01-15"
 },
 {
  "id": "A110",
  "tag": "TS-PC-59",
  "name": "Daisy",
  "dept": "Payments",
  "type": "Desktop",
  "cpu": "Core i5 10th Gen",
  "ram": "8 GB",
  "hdd": "240 GB",
  "sn1": "5ZUFH9DW504474N",
  "sn2": "5ZFUH9DW501789X",
  "periph": {
   "headphone": true,
   "speaker": false,
   "ipPhone": false,
   "webcam": false,
   "mobileStand": false
  },
  "status": "Assigned",
  "date": "2023-01-31"
 },
 {
  "id": "A111",
  "tag": "TS-PC-60",
  "name": "Alvin",
  "dept": "Payments",
  "type": "Desktop",
  "cpu": "Core i5 10th Gen",
  "ram": "8 GB",
  "hdd": "240 GB",
  "sn1": "4PWLH4TT500611M",
  "sn2": "5DNEH4TT802048L",
  "periph": {
   "headphone": true,
   "speaker": false,
   "ipPhone": false,
   "webcam": false,
   "mobileStand": true
  },
  "status": "Assigned",
  "date": "2023-02-27"
 },
 {
  "id": "A112",
  "tag": "TS-PC-61",
  "name": "Day Shift (Shared)",
  "dept": "Payments",
  "type": "Desktop",
  "cpu": "Core i5 10th Gen",
  "ram": "8 GB",
  "hdd": "240 GB",
  "sn1": "4PWLH4TTA00138Z",
  "sn2": "4PWLH4TT500070P",
  "periph": {
   "headphone": true,
   "speaker": false,
   "ipPhone": false,
   "webcam": false,
   "mobileStand": false
  },
  "status": "Assigned",
  "date": "2023-02-22"
 },
 {
  "id": "A113",
  "tag": "TS-PC-73",
  "name": "Sandy",
  "dept": "Payments",
  "type": "Desktop",
  "cpu": "Core i5 10th Gen",
  "ram": "8 GB",
  "hdd": "240 GB",
  "sn1": "5DNEH4TT803030H",
  "sn2": "5DNEH4TT804698M",
  "periph": {
   "headphone": true,
   "speaker": false,
   "ipPhone": false,
   "webcam": false,
   "mobileStand": false
  },
  "status": "Assigned",
  "date": "2023-01-09"
 },
 {
  "id": "A114",
  "tag": "TS-PC-178",
  "name": "Cooper",
  "dept": "Payments",
  "type": "Desktop",
  "cpu": "Core i5 12th Gen",
  "ram": "16 GB",
  "hdd": "240 GB",
  "sn1": "4PWLH4TRB00559W",
  "sn2": "4PWLH4TTA00250B",
  "periph": {
   "headphone": true,
   "speaker": true,
   "ipPhone": false,
   "webcam": false,
   "mobileStand": true
  },
  "status": "Assigned",
  "date": "2023-02-27"
 },
 {
  "id": "A115",
  "tag": "TS-PC-65",
  "name": "Albert",
  "dept": "Payments",
  "type": "Desktop",
  "cpu": "Core i5 9th Gen",
  "ram": "16 GB",
  "hdd": "480 GB",
  "sn1": "4PWLH4TTA00180D",
  "sn2": "4PWLH4TT500722X",
  "periph": {
   "headphone": true,
   "speaker": false,
   "ipPhone": true,
   "webcam": false,
   "mobileStand": false
  },
  "status": "Assigned",
  "date": "2023-02-17"
 },
 {
  "id": "A116",
  "tag": "TS-PC-52",
  "name": "Elvish",
  "dept": "Payments",
  "type": "Desktop",
  "cpu": "Core i5 9th Gen",
  "ram": "8 GB",
  "hdd": "240 GB",
  "sn1": "5DNEH4TT801557X",
  "sn2": "4PWLH4TT501140H",
  "periph": {
   "headphone": true,
   "speaker": false,
   "ipPhone": false,
   "webcam": false,
   "mobileStand": false
  },
  "status": "Assigned",
  "date": "2023-01-10"
 },
 {
  "id": "A117",
  "tag": "TS-PC-51",
  "name": "Nick",
  "dept": "Payments",
  "type": "Desktop",
  "cpu": "Core i5 10th Gen",
  "ram": "24 GB",
  "hdd": "240 GB",
  "sn1": "5ZUFH9DW600568Z",
  "sn2": "0DB9HNAT603603P",
  "periph": {
   "headphone": true,
   "speaker": true,
   "ipPhone": true,
   "webcam": false,
   "mobileStand": false
  },
  "status": "Assigned",
  "date": "2023-02-09"
 },
 {
  "id": "A118",
  "tag": "TS-PC-50",
  "name": "Darwin",
  "dept": "Payments",
  "type": "Desktop",
  "cpu": "Core i5 10th Gen",
  "ram": "8 GB",
  "hdd": "240 GB",
  "sn1": "4PWLH4TT800023K",
  "sn2": "4PWLH4TW400275J",
  "periph": {
   "headphone": true,
   "speaker": false,
   "ipPhone": false,
   "webcam": false,
   "mobileStand": false
  },
  "status": "Assigned",
  "date": "2023-01-19"
 },
 {
  "id": "A119",
  "tag": "TS-PC-29",
  "name": "Kyle",
  "dept": "Mindhives",
  "type": "Desktop",
  "cpu": "Core i5 12th Gen",
  "ram": "16 GB",
  "hdd": "450 GB / 2 TB",
  "sn1": "0WPLHNCV604246N",
  "sn2": "0WPLHNCY406N38D",
  "periph": {
   "headphone": false,
   "speaker": false,
   "ipPhone": false,
   "webcam": false,
   "mobileStand": false
  },
  "status": "Assigned",
  "date": "2023-01-12"
 },
 {
  "id": "A120",
  "tag": "(untagged)",
  "name": "Charlie",
  "dept": "Mindhives",
  "type": "Mac Mini",
  "cpu": "Apple Mac mini",
  "ram": null,
  "hdd": null,
  "sn1": "5ZHXH9TXA00297Z",
  "sn2": "7DU3H9DL101116V",
  "periph": {
   "headphone": true,
   "speaker": false,
   "ipPhone": false,
   "webcam": false,
   "mobileStand": false
  },
  "status": "Assigned",
  "date": "2023-02-04"
 },
 {
  "id": "A121",
  "tag": "TS-PC-191",
  "name": "Miles",
  "dept": "Mindhives",
  "type": "Desktop",
  "cpu": "Core i5 10th Gen",
  "ram": "8 GB",
  "hdd": "240 GB",
  "sn1": "0WPLHNCY407086X",
  "sn2": "BZUTH4TN301043T",
  "periph": {
   "headphone": false,
   "speaker": false,
   "ipPhone": false,
   "webcam": false,
   "mobileStand": false
  },
  "status": "Assigned",
  "date": "2023-01-30"
 },
 {
  "id": "A122",
  "tag": "TS-PC-192",
  "name": "Jane",
  "dept": "Mindhives",
  "type": "Desktop",
  "cpu": "Core i5 12th Gen",
  "ram": "16 GB",
  "hdd": "480 GB",
  "sn1": "7DU3H9DYA03067H",
  "sn2": "7DU3H9DYA03077W",
  "periph": {
   "headphone": false,
   "speaker": false,
   "ipPhone": false,
   "webcam": false,
   "mobileStand": false
  },
  "status": "Assigned",
  "date": "2023-01-25"
 },
 {
  "id": "A123",
  "tag": "TS-PC-24",
  "name": "Peter",
  "dept": "Mindhives",
  "type": "Desktop",
  "cpu": "Core i5 12th Gen",
  "ram": "16 GB",
  "hdd": "480 GB",
  "sn1": "5ZH4H9TX500179J",
  "sn2": "5ZH4H9TX504243B",
  "periph": {
   "headphone": false,
   "speaker": false,
   "ipPhone": false,
   "webcam": false,
   "mobileStand": false
  },
  "status": "Assigned",
  "date": "2023-01-18"
 },
 {
  "id": "A124",
  "tag": "TS-PC-22",
  "name": "Rihana",
  "dept": "Mindhives",
  "type": "Desktop",
  "cpu": "Core i5 12th Gen",
  "ram": "16 GB",
  "hdd": "480 GB",
  "sn1": "5ZUFH9JX500558A",
  "sn2": "5ZUFH9JX500607N",
  "periph": {
   "headphone": true,
   "speaker": false,
   "ipPhone": false,
   "webcam": false,
   "mobileStand": false
  },
  "status": "Assigned",
  "date": "2023-01-28"
 },
 {
  "id": "A125",
  "tag": "TS-PC-19",
  "name": "Ray",
  "dept": "Mindhives",
  "type": "Desktop",
  "cpu": "Core i5 12th Gen",
  "ram": "16 GB",
  "hdd": "480 GB",
  "sn1": "5ZHXH9TXA00467T",
  "sn2": "5ZHXH9TX806419R",
  "periph": {
   "headphone": true,
   "speaker": false,
   "ipPhone": false,
   "webcam": false,
   "mobileStand": false
  },
  "status": "Assigned",
  "date": "2023-02-22"
 },
 {
  "id": "A126",
  "tag": "TS-PC-190",
  "name": "Revin",
  "dept": "Mindhives",
  "type": "Desktop",
  "cpu": "Core i5 12th Gen",
  "ram": "16 GB",
  "hdd": "480 GB",
  "sn1": "0WTLHNCY407681K",
  "sn2": "52UFH9JX300944H",
  "periph": {
   "headphone": false,
   "speaker": false,
   "ipPhone": false,
   "webcam": false,
   "mobileStand": false
  },
  "status": "Assigned",
  "date": "2023-01-20"
 },
 {
  "id": "A127",
  "tag": "TS-PC-193",
  "name": "Theo",
  "dept": "Mindhives",
  "type": "Desktop",
  "cpu": "Core i7 14th Gen",
  "ram": "16 GB",
  "hdd": "480 GB",
  "sn1": "7DU3H9DYA03047D",
  "sn2": "7DU3H9DL101155K",
  "periph": {
   "headphone": false,
   "speaker": false,
   "ipPhone": false,
   "webcam": false,
   "mobileStand": false
  },
  "status": "Assigned",
  "date": "2023-01-26"
 },
 {
  "id": "A128",
  "tag": "TS-PC-194",
  "name": "Colt",
  "dept": "Mindhives",
  "type": "Desktop",
  "cpu": "Core i5 12th Gen",
  "ram": "32 GB",
  "hdd": "480 GB & 240 GB",
  "sn1": "7DU3H9DL101127K",
  "sn2": "7DU3H9DL101167D",
  "periph": {
   "headphone": false,
   "speaker": false,
   "ipPhone": false,
   "webcam": false,
   "mobileStand": false
  },
  "status": "Assigned",
  "date": "2023-01-26"
 },
 {
  "id": "A129",
  "tag": "TS-PC-17",
  "name": "Rylee",
  "dept": "Smart Key",
  "type": "Desktop",
  "cpu": "Core i5 10th Gen",
  "ram": "16 GB",
  "hdd": "480 GB",
  "sn1": "5ZHXH9TXA004389",
  "sn2": "5ZUFH9JX300744N",
  "periph": {
   "headphone": true,
   "speaker": false,
   "ipPhone": false,
   "webcam": false,
   "mobileStand": false
  },
  "status": "Assigned",
  "date": "2023-01-29"
 },
 {
  "id": "A130",
  "tag": "TS-PC-16",
  "name": "Scott",
  "dept": "Smart Key",
  "type": "Desktop",
  "cpu": "Core i5 12th Gen",
  "ram": "16 GB",
  "hdd": "480 GB",
  "sn1": "5ZHXH9TX804221M",
  "sn2": "5ZHXH9TX804172B",
  "periph": {
   "headphone": true,
   "speaker": false,
   "ipPhone": true,
   "webcam": true,
   "mobileStand": false
  },
  "status": "Assigned",
  "date": "2023-01-19"
 },
 {
  "id": "A131",
  "tag": "TS-PC-9",
  "name": "Steve Smith",
  "dept": "Smart Key",
  "type": "Desktop",
  "cpu": "Core i5 10th Gen",
  "ram": "16 GB",
  "hdd": "480 GB",
  "sn1": "5ZHXH9TXA01795Y",
  "sn2": "5ZHXH9TX904628P",
  "periph": {
   "headphone": true,
   "speaker": false,
   "ipPhone": false,
   "webcam": false,
   "mobileStand": false
  },
  "status": "Assigned",
  "date": "2023-02-13"
 },
 {
  "id": "A132",
  "tag": "TS-PC-15",
  "name": "Daryl",
  "dept": "Smart Key",
  "type": "Desktop",
  "cpu": "Core i5 10th Gen",
  "ram": "16 GB",
  "hdd": "480 GB",
  "sn1": "5ZUFH9JX300793W",
  "sn2": "5ZHXH9TX701584H",
  "periph": {
   "headphone": true,
   "speaker": false,
   "ipPhone": true,
   "webcam": false,
   "mobileStand": false
  },
  "status": "Assigned",
  "date": "2023-02-27"
 },
 {
  "id": "A133",
  "tag": "TS-PC-14",
  "name": "Alex",
  "dept": "Smart Key",
  "type": "Desktop",
  "cpu": "Core i5 10th Gen",
  "ram": "16 GB",
  "hdd": "480 GB",
  "sn1": "5ZUFH9JXT00943T",
  "sn2": "5ZH4H9TX503908F",
  "periph": {
   "headphone": true,
   "speaker": false,
   "ipPhone": true,
   "webcam": false,
   "mobileStand": false
  },
  "status": "Assigned",
  "date": "2023-02-19"
 },
 {
  "id": "A134",
  "tag": "TS-PC-13",
  "name": "Emily",
  "dept": "Smart Key",
  "type": "Desktop",
  "cpu": "Core i5 11th Gen",
  "ram": "16 GB",
  "hdd": "480 GB",
  "sn1": "5ZUFH9JX300753B",
  "sn2": "5ZH4H9TX504318A",
  "periph": {
   "headphone": true,
   "speaker": false,
   "ipPhone": false,
   "webcam": false,
   "mobileStand": false
  },
  "status": "Assigned",
  "date": "2023-02-06"
 },
 {
  "id": "A135",
  "tag": "TS-PC-02",
  "name": "Alden",
  "dept": "Smart Key",
  "type": "Desktop",
  "cpu": "Core i5 10th Gen",
  "ram": "16 GB",
  "hdd": "480 GB",
  "sn1": "5ZH4H9TX504199Y",
  "sn2": "5ZH4H9TX503901A",
  "periph": {
   "headphone": true,
   "speaker": false,
   "ipPhone": false,
   "webcam": false,
   "mobileStand": false
  },
  "status": "Assigned",
  "date": "2023-02-26"
 },
 {
  "id": "A136",
  "tag": "TS-PC-195",
  "name": "Blaze",
  "dept": "Smart Key",
  "type": "Desktop",
  "cpu": "Core i5 10th Gen",
  "ram": "16 GB",
  "hdd": "480 GB",
  "sn1": "5ZHXH9TX605008T",
  "sn2": "7DU3H9DLI0022R",
  "periph": {
   "headphone": true,
   "speaker": false,
   "ipPhone": false,
   "webcam": false,
   "mobileStand": false
  },
  "status": "Assigned",
  "date": "2023-01-21"
 },
 {
  "id": "A137",
  "tag": "TS-PC-11",
  "name": "John",
  "dept": "Smart Key",
  "type": "Desktop",
  "cpu": "Core i5 10th Gen",
  "ram": "16 GB",
  "hdd": "480 GB",
  "sn1": "4PWLH4TT500721L",
  "sn2": "4PWLH4TW400273W",
  "periph": {
   "headphone": true,
   "speaker": false,
   "ipPhone": true,
   "webcam": true,
   "mobileStand": false
  },
  "status": "Assigned",
  "date": "2023-02-18"
 },
 {
  "id": "A138",
  "tag": "TS-PC-12",
  "name": "Otis",
  "dept": "Smart Key",
  "type": "Desktop",
  "cpu": "Core i5 10th Gen",
  "ram": "32 GB",
  "hdd": "480 GB",
  "sn1": "5ZH4H9TX500011V",
  "sn2": "0WPLHNCI407632D",
  "periph": {
   "headphone": true,
   "speaker": false,
   "ipPhone": true,
   "webcam": false,
   "mobileStand": false
  },
  "status": "Assigned",
  "date": "2023-02-18"
 },
 {
  "id": "A139",
  "tag": "TS-PC-196",
  "name": "Olive",
  "dept": "Smart Key",
  "type": "Desktop",
  "cpu": "Core i5 12th Gen",
  "ram": "16 GB",
  "hdd": "480 GB",
  "sn1": "4PWLH4TT100436A",
  "sn2": "4PWLH4TW500439R",
  "periph": {
   "headphone": true,
   "speaker": false,
   "ipPhone": false,
   "webcam": false,
   "mobileStand": false
  },
  "status": "Assigned",
  "date": "2023-01-31"
 },
 {
  "id": "A140",
  "tag": "TS-PC-04",
  "name": "Rachel",
  "dept": "Smart Key",
  "type": "Desktop",
  "cpu": "Core i5 12th Gen",
  "ram": "16 GB",
  "hdd": "480 GB",
  "sn1": "5ZUFH9DW503240K",
  "sn2": "5ZUFH9DW502735Y",
  "periph": {
   "headphone": true,
   "speaker": false,
   "ipPhone": false,
   "webcam": true,
   "mobileStand": false
  },
  "status": "Assigned",
  "date": "2023-01-10"
 },
 {
  "id": "A141",
  "tag": "TS-PC-165",
  "name": "Gary",
  "dept": "Smart Key",
  "type": "Desktop",
  "cpu": "Core i5 12th Gen",
  "ram": "16 GB",
  "hdd": "480 GB",
  "sn1": "5ZUFH9DW600576P",
  "sn2": "7DU3H9DL101144B",
  "periph": {
   "headphone": true,
   "speaker": false,
   "ipPhone": true,
   "webcam": true,
   "mobileStand": false
  },
  "status": "Assigned",
  "date": "2023-02-14"
 },
 {
  "id": "A142",
  "tag": "TS-PC-197",
  "name": "Dave",
  "dept": "Smart Key",
  "type": "Desktop",
  "cpu": "Core i5 12th Gen",
  "ram": "16 GB",
  "hdd": "480 GB",
  "sn1": "0WPLHNCY407524T",
  "sn2": "5ZHX9TX806437D",
  "periph": {
   "headphone": true,
   "speaker": false,
   "ipPhone": false,
   "webcam": false,
   "mobileStand": false
  },
  "status": "Assigned",
  "date": "2023-01-27"
 },
 {
  "id": "A143",
  "tag": "TS-PC-07",
  "name": "Shaq",
  "dept": "Smart Key",
  "type": "Desktop",
  "cpu": "Core i5 10th Gen",
  "ram": "8 GB",
  "hdd": "240 GB",
  "sn1": "4PWLH4TTA00270D",
  "sn2": "4PWLH4TT500733N",
  "periph": {
   "headphone": true,
   "speaker": true,
   "ipPhone": false,
   "webcam": false,
   "mobileStand": false
  },
  "status": "Assigned",
  "date": "2023-02-09"
 },
 {
  "id": "A144",
  "tag": "TS-PC-08",
  "name": "Roy",
  "dept": "Smart Key",
  "type": "Desktop",
  "cpu": "Core i5 11th Gen",
  "ram": "16 GB",
  "hdd": "480 GB",
  "sn1": "5ZHX119TX603254T",
  "sn2": "4PWLHUTW400461Z",
  "periph": {
   "headphone": true,
   "speaker": false,
   "ipPhone": true,
   "webcam": true,
   "mobileStand": false
  },
  "status": "Assigned",
  "date": "2023-02-22"
 },
 {
  "id": "A145",
  "tag": "TS-PC-18",
  "name": "Ricky",
  "dept": "Smart Key",
  "type": "Desktop",
  "cpu": "Core i5 12th Gen",
  "ram": "16 GB",
  "hdd": "480 GB",
  "sn1": "7DU3H9DVA02053F",
  "sn2": "5ZHXH9TX904573X",
  "periph": {
   "headphone": true,
   "speaker": false,
   "ipPhone": false,
   "webcam": true,
   "mobileStand": true
  },
  "status": "Assigned",
  "date": "2023-02-08"
 },
 {
  "id": "A146",
  "tag": "TS-PC-03",
  "name": "Danny",
  "dept": "Smart Key",
  "type": "Desktop",
  "cpu": "Core i5 9th Gen",
  "ram": "16 GB",
  "hdd": "240 GB",
  "sn1": "4PWLH4TW500382R",
  "sn2": "4PWLH4TW500401K",
  "periph": {
   "headphone": true,
   "speaker": false,
   "ipPhone": false,
   "webcam": true,
   "mobileStand": true
  },
  "status": "Assigned",
  "date": "2023-01-17"
 },
 {
  "id": "A147",
  "tag": "TS-PC-198",
  "name": "Tia",
  "dept": "Watches",
  "type": "Desktop",
  "cpu": "Core i5 10th Gen",
  "ram": "8 GB",
  "hdd": "240 GB",
  "sn1": "5ZHXH9TX804406F",
  "sn2": "0WPLHNCY407674F",
  "periph": {
   "headphone": true,
   "speaker": true,
   "ipPhone": true,
   "webcam": false,
   "mobileStand": false
  },
  "status": "Assigned",
  "date": "2023-02-20"
 },
 {
  "id": "A148",
  "tag": "TS-PC-161",
  "name": "Day Shift (Shared)",
  "dept": "Watches",
  "type": "Desktop",
  "cpu": "Core i5 9th Gen",
  "ram": "16 GB",
  "hdd": "480 GB",
  "sn1": "4PWLH4TW500433M",
  "sn2": "5ZH4H9TX504241K",
  "periph": {
   "headphone": true,
   "speaker": true,
   "ipPhone": false,
   "webcam": false,
   "mobileStand": false
  },
  "status": "Assigned",
  "date": "2023-01-25"
 },
 {
  "id": "A149",
  "tag": "TS-PC-167",
  "name": "Dexter",
  "dept": "Watches",
  "type": "Desktop",
  "cpu": "Core i5 10th Gen",
  "ram": "16 GB",
  "hdd": "240 GB",
  "sn1": "5ZHXH9TX804213F",
  "sn2": "5ZH4H9TX504325X",
  "periph": {
   "headphone": true,
   "speaker": true,
   "ipPhone": false,
   "webcam": false,
   "mobileStand": false
  },
  "status": "Assigned",
  "date": "2023-01-09"
 },
 {
  "id": "A150",
  "tag": "TS-PC-166",
  "name": "Addy",
  "dept": "Watches",
  "type": "Desktop",
  "cpu": "Core i5 9th Gen",
  "ram": "8 GB",
  "hdd": "240 GB",
  "sn1": "5ZHXH9TXA00442L",
  "sn2": "5ZH4H9TX504351A",
  "periph": {
   "headphone": true,
   "speaker": true,
   "ipPhone": true,
   "webcam": false,
   "mobileStand": true
  },
  "status": "Assigned",
  "date": "2023-02-15"
 },
 {
  "id": "A151",
  "tag": "TS-PC-46",
  "name": "Azee",
  "dept": "Watches",
  "type": "Desktop",
  "cpu": "Core i5 9th Gen",
  "ram": "8 GB",
  "hdd": "240 GB",
  "sn1": "7DU3H9DYB01244L",
  "sn2": "7DU3H9DYC01080R",
  "periph": {
   "headphone": true,
   "speaker": true,
   "ipPhone": true,
   "webcam": false,
   "mobileStand": false
  },
  "status": "Assigned",
  "date": "2023-01-31"
 },
 {
  "id": "A152",
  "tag": "TS-PC-35",
  "name": "Kayra New",
  "dept": "Watches",
  "type": "Desktop",
  "cpu": "Core i5 10th Gen",
  "ram": "16 GB",
  "hdd": "480 GB",
  "sn1": "4PWLH4TTA00346J",
  "sn2": "4PWLH4TW400269M",
  "periph": {
   "headphone": true,
   "speaker": true,
   "ipPhone": false,
   "webcam": false,
   "mobileStand": false
  },
  "status": "Assigned",
  "date": "2023-02-21"
 },
 {
  "id": "A153",
  "tag": "TS-PC-05",
  "name": "Kayra Old",
  "dept": "Watches",
  "type": "Desktop",
  "cpu": "Core i5 10th Gen",
  "ram": "12 GB",
  "hdd": "240 GB",
  "sn1": "0WPLHLAXB02609V",
  "sn2": "0WPLHNAXB02567F",
  "periph": {
   "headphone": true,
   "speaker": true,
   "ipPhone": false,
   "webcam": false,
   "mobileStand": false
  },
  "status": "Assigned",
  "date": "2023-02-16"
 },
 {
  "id": "A154",
  "tag": "TS-PC-168",
  "name": "Roman",
  "dept": "Watches",
  "type": "Desktop",
  "cpu": "Core i5 10th Gen",
  "ram": "32 GB",
  "hdd": "480 GB",
  "sn1": "4PWLH4TW400282A",
  "sn2": "4PWLH4TW400271X",
  "periph": {
   "headphone": true,
   "speaker": true,
   "ipPhone": true,
   "webcam": true,
   "mobileStand": false
  },
  "status": "Assigned",
  "date": "2023-02-10"
 },
 {
  "id": "A155",
  "tag": "TS-PC-36",
  "name": "Kendrick",
  "dept": "Watches",
  "type": "Desktop",
  "cpu": "Core i5 10th Gen",
  "ram": "8 GB",
  "hdd": "240 GB",
  "sn1": "5ZUFH9BW503685K",
  "sn2": "BZUTH4TR400479K",
  "periph": {
   "headphone": true,
   "speaker": true,
   "ipPhone": false,
   "webcam": false,
   "mobileStand": true
  },
  "status": "Assigned",
  "date": "2023-02-27"
 },
 {
  "id": "A156",
  "tag": "TS-PC-175",
  "name": "David",
  "dept": "Watches",
  "type": "Desktop",
  "cpu": "Core i5 12th Gen",
  "ram": "16 GB",
  "hdd": "480 GB",
  "sn1": "5ZUFH9DW502227H",
  "sn2": "5ZUFH9DW500935Y",
  "periph": {
   "headphone": true,
   "speaker": false,
   "ipPhone": false,
   "webcam": false,
   "mobileStand": false
  },
  "status": "Assigned",
  "date": "2023-01-30"
 },
 {
  "id": "A157",
  "tag": "TS-PC-06",
  "name": "Roger",
  "dept": "Watches",
  "type": "Desktop",
  "cpu": "Core i5 12th Gen",
  "ram": "16 GB",
  "hdd": "480 GB",
  "sn1": "5ZHXH9TX8037027T",
  "sn2": "5ZHXH9TX806438E",
  "periph": {
   "headphone": true,
   "speaker": false,
   "ipPhone": false,
   "webcam": true,
   "mobileStand": false
  },
  "status": "Assigned",
  "date": "2023-02-17"
 },
 {
  "id": "A158",
  "tag": "TS-PC-199",
  "name": "Drek",
  "dept": "Watches",
  "type": "Desktop",
  "cpu": "Core i5 12th Gen",
  "ram": "16 GB",
  "hdd": "480 GB",
  "sn1": "5ZHXH9TX803666A",
  "sn2": "5ZHXH9TX806424D",
  "periph": {
   "headphone": true,
   "speaker": true,
   "ipPhone": false,
   "webcam": false,
   "mobileStand": false
  },
  "status": "Assigned",
  "date": "2023-01-28"
 },
 {
  "id": "A159",
  "tag": "TS-PC-33",
  "name": "Remo",
  "dept": "Watches",
  "type": "Desktop",
  "cpu": "Core i5 10th Gen",
  "ram": "8 GB",
  "hdd": "240 GB",
  "sn1": "4PWLH4TRC00016T",
  "sn2": "5ZHXH9TX806482Z",
  "periph": {
   "headphone": true,
   "speaker": true,
   "ipPhone": false,
   "webcam": false,
   "mobileStand": true
  },
  "status": "Assigned",
  "date": "2023-01-20"
 },
 {
  "id": "A160",
  "tag": "TS-PC-180",
  "name": "Cyrus",
  "dept": "Watches",
  "type": "Desktop",
  "cpu": "Core i5 12th Gen",
  "ram": "16 GB",
  "hdd": "480 GB",
  "sn1": "7DU3H9DYC01076A",
  "sn2": "5ZHXH9TX603284H",
  "periph": {
   "headphone": true,
   "speaker": false,
   "ipPhone": false,
   "webcam": false,
   "mobileStand": false
  },
  "status": "Assigned",
  "date": "2023-02-18"
 },
 {
  "id": "A161",
  "tag": "TS-PC-37",
  "name": "Dominic",
  "dept": "Watches",
  "type": "Desktop",
  "cpu": "Core i5 10th Gen",
  "ram": "16 GB",
  "hdd": "480 GB",
  "sn1": "5ZHX49TX803665K",
  "sn2": "5ZHX49TX806444X",
  "periph": {
   "headphone": true,
   "speaker": true,
   "ipPhone": false,
   "webcam": false,
   "mobileStand": false
  },
  "status": "Assigned",
  "date": "2023-01-09"
 },
 {
  "id": "A162",
  "tag": "TS-PC-25",
  "name": "Day Shift (Shared)",
  "dept": "MIS / IT",
  "type": "Desktop",
  "cpu": "Core i5 10th Gen",
  "ram": "16 GB",
  "hdd": "480 GB",
  "sn1": "7DU3H9DYA03087T",
  "sn2": "5ZH4H9TX504281X",
  "periph": {
   "headphone": false,
   "speaker": false,
   "ipPhone": false,
   "webcam": false,
   "mobileStand": false
  },
  "status": "Assigned",
  "date": "2023-01-13"
 },
 {
  "id": "A163",
  "tag": "TS-PC-30",
  "name": "Santosh",
  "dept": "MIS / IT",
  "type": "Desktop",
  "cpu": "Core i5 12th Gen",
  "ram": "24 GB",
  "hdd": "480 GB",
  "sn1": "7DU3H9DYB01284W",
  "sn2": "7DU3H9DYB01278J",
  "periph": {
   "headphone": true,
   "speaker": false,
   "ipPhone": false,
   "webcam": false,
   "mobileStand": false
  },
  "status": "Assigned",
  "date": "2023-02-25"
 },
 {
  "id": "A164",
  "tag": "TS-PC-48",
  "name": "Sachin",
  "dept": "MIS / IT",
  "type": "Desktop",
  "cpu": "Core i5 10th Gen",
  "ram": "16 GB",
  "hdd": "480 GB",
  "sn1": "5ZH4H9TX504323N",
  "sn2": "4PWLH4TTA00019R",
  "periph": {
   "headphone": false,
   "speaker": false,
   "ipPhone": false,
   "webcam": false,
   "mobileStand": false
  },
  "status": "Assigned",
  "date": "2023-02-26"
 },
 {
  "id": "A165",
  "tag": "TS-PC-49",
  "name": "Mahendra",
  "dept": "MIS / IT",
  "type": "Desktop",
  "cpu": "Core i5 11th Gen",
  "ram": "16 GB",
  "hdd": "480 GB",
  "sn1": "5ZH4H9TX500064Y",
  "sn2": "4PWLH4TW800109F",
  "periph": {
   "headphone": false,
   "speaker": false,
   "ipPhone": false,
   "webcam": false,
   "mobileStand": false
  },
  "status": "Assigned",
  "date": "2023-01-27"
 },
 {
  "id": "A166",
  "tag": "TS-PC-28",
  "name": null,
  "dept": "IT Stock",
  "type": "Desktop",
  "cpu": null,
  "ram": null,
  "hdd": null,
  "sn1": null,
  "sn2": null,
  "periph": {},
  "status": "Available",
  "date": null
 },
 {
  "id": "A167",
  "tag": "TS-PC-45",
  "name": null,
  "dept": "IT Stock",
  "type": "Desktop",
  "cpu": null,
  "ram": null,
  "hdd": null,
  "sn1": null,
  "sn2": null,
  "periph": {},
  "status": "In Repair",
  "date": null
 },
 {
  "id": "A168",
  "tag": "TS-PC-47",
  "name": null,
  "dept": "IT Stock",
  "type": "Desktop",
  "cpu": null,
  "ram": null,
  "hdd": null,
  "sn1": null,
  "sn2": null,
  "periph": {},
  "status": "Available",
  "date": null
 },
 {
  "id": "A169",
  "tag": "TS-PC-155",
  "name": null,
  "dept": "IT Stock",
  "type": "Desktop",
  "cpu": null,
  "ram": null,
  "hdd": null,
  "sn1": null,
  "sn2": null,
  "periph": {},
  "status": "In Repair",
  "date": null
 }
];
