// Task Source — Purchase Requests page (raise → review → approve/reject procurement requests)
import React, { useState, useEffect } from "react";
import { Icon, ICONS, DeptBadge, Field } from "./components.jsx";
import {
  usePurchaseRequests, useCreatePurchaseRequest, useUpdatePurchaseRequest, useSetPRStatus, useDeletePurchaseRequest, usePurchaseOrders,
  useUploadPRAttachment, useDeletePRAttachment
} from "./api/hooks.js";
import { api } from "./api/client.js";
import { SkeletonTable } from "./Skeleton.jsx";
import { useToast } from "./toasts.jsx";
import { useConfirm } from "./confirm.jsx";
import { DEPARTMENTS, PR_CATEGORIES } from "@its/shared/constants";
import { POGenerateForm } from "./pages-purchase-orders.jsx";

const STATUS_TONE = {
  Pending:  "var(--warn, #b45309)",
  Approved: "var(--success, #15803d)",
  Rejected: "var(--danger, #dc2626)"
};
function PRStatusPill({ status }) {
  const c = STATUS_TONE[status] || "var(--text-3)";
  return <span className="status-pill" style={{ color: c, borderColor: c }}>{status}</span>;
}
function fmtDate(iso) {
  if (!iso) return "—";
  const d = new Date(iso);
  if (isNaN(d)) return "—";
  return d.toLocaleDateString("en-US", { month: "short", day: "numeric", year: "numeric" });
}
function fmtDateTime(iso) {
  if (!iso) return "—";
  const d = new Date(iso);
  if (isNaN(d)) return "—";
  return d.toLocaleString("en-US", { month: "short", day: "numeric", year: "numeric", hour: "numeric", minute: "2-digit" });
}
function fmtMoney(v) {
  if (v == null || v === "") return "—";
  return "₹" + Number(v).toLocaleString("en-IN");
}
function fmtBytes(b) { if (b == null) return ""; return b < 1024 ? b + " B" : (b / 1024).toFixed(1) + " KB"; }
const esc = (s) => String(s ?? "").replace(/[&<>"]/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" }[c]));

const FILTERS = ["All", "Pending", "Approved", "Rejected"];

/* ---------- print-ready PR (opens a clean form + triggers print/save-as-PDF) ----------
   Workflow this exists for: download → print → get it physically signed → scan → Attach file. */
function printPR(pr) {
  const html = `<!doctype html><html><head><meta charset="utf-8"><title>${esc(pr.prNumber)}</title>
  <style>
    *{box-sizing:border-box} body{font:13px/1.5 -apple-system,Segoe UI,Roboto,sans-serif;color:#0f172a;margin:32px;max-width:820px}
    .head{display:flex;justify-content:space-between;align-items:flex-start;border-bottom:2px solid #0f172a;padding-bottom:14px}
    .company .wordmark{font-size:20px;font-weight:800;letter-spacing:.5px;white-space:nowrap}
    .company .sub{color:#64748b;font-size:12px;margin-top:2px;max-width:260px}
    .doc{text-align:right} .doc h2{margin:0;font-size:22px;letter-spacing:.5px} .doc .meta{color:#64748b;font-size:12px;margin-top:4px}
    .grid{display:grid;grid-template-columns:1fr 1fr 1fr;gap:16px 24px;margin:20px 0}
    .lbl{font-size:11px;text-transform:uppercase;letter-spacing:.5px;color:#64748b;margin-bottom:3px}
    .purpose{margin-top:18px} .purpose .box{white-space:pre-wrap;border:1px solid #e2e8f0;border-radius:6px;padding:10px;min-height:48px}
    .sign{display:flex;gap:60px;margin-top:56px}
    .sign .col{flex:1} .sign .line{border-top:1px solid #0f172a;margin-top:46px;padding-top:6px;font-size:11px;color:#64748b}
    .foot{margin-top:30px;color:#94a3b8;font-size:11px;text-align:center;border-top:1px solid #e2e8f0;padding-top:10px}
    @media print{body{margin:0;padding:18px}}
  </style></head>
  <body onload="window.print()">
    <div class="head">
      <div class="company"><div class="wordmark">TASK SOURCE</div>
        <div class="sub">Princes Business Sky park, 701, 702, 703, Indore, Madhya Pradesh 452011</div></div>
      <div class="doc"><h2>PURCHASE REQUEST</h2><div class="meta">${esc(pr.prNumber)}<br>Raised: ${fmtDate(pr.createdAt)}<br>Status: ${esc(pr.status)}</div></div>
    </div>
    <div class="grid">
      <div><div class="lbl">Requested by</div>${esc(pr.requestedBy)}</div>
      <div><div class="lbl">Department</div>${esc(pr.department) || "—"}</div>
      <div><div class="lbl">Category</div>${esc(pr.category) || "—"}</div>
      <div><div class="lbl">Required by</div>${fmtDate(pr.requiredBy)}</div>
      <div><div class="lbl">Estimated cost</div>${fmtMoney(pr.estimatedCost)}</div>
      <div><div class="lbl">Suggested vendors</div>${esc(pr.suggestedVendors) || "—"}</div>
    </div>
    <div class="purpose"><div class="lbl">Business purpose</div><div class="box">${esc(pr.businessPurpose)}</div></div>
    <div class="sign">
      <div class="col"><div class="line">Prepared by IT (name, signature, date)</div></div>
      <div class="col"><div class="line">Approved by Sachin Jat (name, signature, date)</div></div>
    </div>
    <div class="foot">Generated by Task Source IT Asset Tracker</div>
  </body></html>`;
  const w = window.open("", "_blank");
  if (!w) return false;
  w.document.write(html);
  w.document.close();
  return true;
}

/* ---------- attachments manager (e.g. the signed/approved document) — mirrors the PO panel ---------- */
function PRAttachmentsPanel({ pr, canManage }) {
  const { showToast } = useToast();
  const up = useUploadPRAttachment(pr.id, { onSuccess: () => showToast("Attachment added", "success"), onError: (e) => showToast(e.message, "error") });
  const del = useDeletePRAttachment({ onSuccess: () => showToast("Attachment removed", "success"), onError: (e) => showToast(e.message, "error") });
  const onFile = (e) => { const f = e.target.files && e.target.files[0]; if (f) up.mutate(f); e.target.value = ""; };
  const list = pr.attachments || [];
  return (
    <div style={{ marginTop: "var(--sp-14)" }}>
      <div className="field-label">Attachments</div>
      {list.length === 0 ? <div className="cell-muted" style={{ marginTop: 4 }}>None yet.</div> : (
        <ul style={{ listStyle: "none", padding: 0, margin: "4px 0 0" }}>
          {list.map((a) => (
            <li key={a.id} style={{ display: "flex", alignItems: "center", gap: 8, padding: "3px 0" }}>
              <Icon d={ICONS.template} size={13} />
              <button type="button" onClick={() => api.download(`/purchase-requests/attachments/${a.id}`)}
                style={{ background: "none", border: "none", color: "var(--accent)", cursor: "pointer", textDecoration: "underline", padding: 0 }}>{a.filename}</button>
              <span className="cell-muted">{fmtBytes(a.size)}</span>
              {canManage ? <button type="button" className="icon-btn" onClick={() => del.mutate(a.id)} aria-label="Remove attachment"><Icon d={ICONS.close} size={12} /></button> : null}
            </li>
          ))}
        </ul>
      )}
      {canManage ? (
        <label className="btn btn-secondary btn-sm" style={{ marginTop: "var(--sp-8)", cursor: "pointer" }}>
          <Icon d={ICONS.upload} size={12} /> {up.isPending ? "Uploading…" : "Attach file"}
          <input type="file" hidden onChange={onFile} disabled={up.isPending} />
        </label>
      ) : null}
    </div>
  );
}

/* ---------- create form ---------- */
function NewRequestForm({ onClose }) {
  const [form, setForm] = useState({
    department: "", category: "", businessPurpose: "",
    requiredBy: "", estimatedCost: "", suggestedVendors: ""
  });
  const { showToast } = useToast();
  const create = useCreatePurchaseRequest({
    onSuccess: (pr) => { showToast(`${pr.prNumber} raised`, "success"); onClose(); },
    onError: (e) => showToast(e.message, "error")
  });
  const set = (k) => (e) => setForm((f) => ({ ...f, [k]: e.target.value }));
  const valid = form.department && form.category && form.businessPurpose.trim();

  const submit = (e) => {
    e.preventDefault();
    if (!valid) return;
    // requestedBy is auto-filled server-side from the session — intentionally omitted here.
    create.mutate({
      department: form.department,
      category: form.category,
      businessPurpose: form.businessPurpose.trim(),
      requiredBy: form.requiredBy || null,
      estimatedCost: form.estimatedCost !== "" ? Number(form.estimatedCost) : null,
      suggestedVendors: form.suggestedVendors.trim() || null
    });
  };

  return (
    <form className="table-card" style={{ padding: "var(--sp-16)", marginBottom: "var(--sp-16)" }} onSubmit={submit}>
      <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: "var(--sp-12)" }}>
        <strong>New Purchase Request</strong>
        <button type="button" className="icon-btn" onClick={onClose} aria-label="Cancel"><Icon d={ICONS.close} size={15} /></button>
      </div>
      <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(220px, 1fr))", gap: "var(--sp-12)" }}>
        <label className="pr-field">
          <span className="field-label">Department *</span>
          <select className="input" value={form.department} onChange={set("department")} required>
            <option value="">Select department…</option>
            {DEPARTMENTS.map((d) => <option key={d} value={d}>{d}</option>)}
          </select>
        </label>
        <label className="pr-field">
          <span className="field-label">Category *</span>
          <select className="input" value={form.category} onChange={set("category")} required>
            <option value="">Select category…</option>
            {PR_CATEGORIES.map((c) => <option key={c} value={c}>{c}</option>)}
          </select>
        </label>
        <label className="pr-field">
          <span className="field-label">Required by</span>
          <input className="input" type="date" value={form.requiredBy} onChange={set("requiredBy")} />
        </label>
        <label className="pr-field">
          <span className="field-label">Estimated cost (₹)</span>
          <input className="input" type="number" min="0" step="any" placeholder="0"
            value={form.estimatedCost} onChange={set("estimatedCost")} />
        </label>
        <label className="pr-field" style={{ gridColumn: "1 / -1" }}>
          <span className="field-label">Business purpose *</span>
          <textarea className="input" rows={2} placeholder="Why is this item/service required?"
            value={form.businessPurpose} onChange={set("businessPurpose")} required />
        </label>
        <label className="pr-field" style={{ gridColumn: "1 / -1" }}>
          <span className="field-label">Suggested vendors</span>
          <input className="input" placeholder="e.g. Dell, HP, Lenovo"
            value={form.suggestedVendors} onChange={set("suggestedVendors")} />
        </label>
      </div>
      <div style={{ display: "flex", gap: "var(--sp-8)", justifyContent: "flex-end", marginTop: "var(--sp-12)" }}>
        <button type="button" className="btn btn-secondary btn-sm" onClick={onClose}>Cancel</button>
        <button type="submit" className="btn btn-primary btn-sm" disabled={!valid || create.isPending}>
          {create.isPending ? "Submitting…" : "Submit request"}
        </button>
      </div>
    </form>
  );
}

/* ---------- edit form (Pending only, enforced server-side too) ---------- */
function PREditModal({ pr, onClose }) {
  const [form, setForm] = useState({
    department: pr.department || "",
    category: pr.category || "",
    businessPurpose: pr.businessPurpose || "",
    requiredBy: pr.requiredBy || "",
    estimatedCost: pr.estimatedCost != null ? String(pr.estimatedCost) : "",
    suggestedVendors: pr.suggestedVendors || ""
  });
  const { showToast } = useToast();
  const update = useUpdatePurchaseRequest({
    onSuccess: (r) => { showToast(`${r.prNumber} updated`, "success"); onClose(); },
    onError: (e) => showToast(e.message, "error")
  });
  const set = (k) => (e) => setForm((f) => ({ ...f, [k]: e.target.value }));
  const valid = form.department && form.category && form.businessPurpose.trim();

  useEffect(() => {
    const onKey = (e) => { if (e.key === "Escape") onClose(); };
    document.addEventListener("keydown", onKey);
    return () => document.removeEventListener("keydown", onKey);
  }, [onClose]);

  const submit = (e) => {
    e.preventDefault();
    if (!valid) return;
    update.mutate({
      id: pr.id,
      input: {
        department: form.department,
        category: form.category,
        businessPurpose: form.businessPurpose.trim(),
        requiredBy: form.requiredBy || null,
        estimatedCost: form.estimatedCost !== "" ? Number(form.estimatedCost) : null,
        suggestedVendors: form.suggestedVendors.trim() || null
      }
    });
  };

  return (
    <div style={{ position: "fixed", inset: 0, background: "rgba(15,23,42,0.45)", display: "flex", alignItems: "center", justifyContent: "center", zIndex: 1000, padding: 16 }}
      onClick={onClose} role="dialog" aria-modal="true" aria-label={`Edit ${pr.prNumber}`}>
      <form className="table-card" style={{ maxWidth: 620, width: "100%", padding: "var(--sp-20)", maxHeight: "90vh", overflowY: "auto" }}
        onClick={(e) => e.stopPropagation()} onSubmit={submit}>
        <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: "var(--sp-16)" }}>
          <strong>Edit {pr.prNumber}</strong>
          <button type="button" className="icon-btn" onClick={onClose} aria-label="Cancel"><Icon d={ICONS.close} size={15} /></button>
        </div>
        <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(220px, 1fr))", gap: "var(--sp-12)" }}>
          <label className="pr-field">
            <span className="field-label">Department *</span>
            <select className="input" value={form.department} onChange={set("department")} required>
              <option value="">Select department…</option>
              {DEPARTMENTS.map((d) => <option key={d} value={d}>{d}</option>)}
            </select>
          </label>
          <label className="pr-field">
            <span className="field-label">Category *</span>
            <select className="input" value={form.category} onChange={set("category")} required>
              <option value="">Select category…</option>
              {PR_CATEGORIES.map((c) => <option key={c} value={c}>{c}</option>)}
            </select>
          </label>
          <label className="pr-field">
            <span className="field-label">Required by</span>
            <input className="input" type="date" value={form.requiredBy} onChange={set("requiredBy")} />
          </label>
          <label className="pr-field">
            <span className="field-label">Estimated cost (₹)</span>
            <input className="input" type="number" min="0" step="any" placeholder="0"
              value={form.estimatedCost} onChange={set("estimatedCost")} />
          </label>
          <label className="pr-field" style={{ gridColumn: "1 / -1" }}>
            <span className="field-label">Business purpose *</span>
            <textarea className="input" rows={2} placeholder="Why is this item/service required?"
              value={form.businessPurpose} onChange={set("businessPurpose")} required />
          </label>
          <label className="pr-field" style={{ gridColumn: "1 / -1" }}>
            <span className="field-label">Suggested vendors</span>
            <input className="input" placeholder="e.g. Dell, HP, Lenovo"
              value={form.suggestedVendors} onChange={set("suggestedVendors")} />
          </label>
        </div>
        <div style={{ display: "flex", gap: "var(--sp-8)", justifyContent: "flex-end", marginTop: "var(--sp-16)", borderTop: "1px solid var(--border)", paddingTop: "var(--sp-14)" }}>
          <button type="button" className="btn btn-secondary btn-sm" onClick={onClose}>Cancel</button>
          <button type="submit" className="btn btn-primary btn-sm" disabled={!valid || update.isPending}>
            {update.isPending ? "Saving…" : "Save changes"}
          </button>
        </div>
      </form>
    </div>
  );
}

/* ---------- detail / review modal ---------- */
// Approvers open this to VERIFY the full request before deciding. Approve/Reject live here
// (not in the table) so an Admin can't act without seeing the details first.
function PRDetailModal({ pr, canAdmin, canManage, canApprove, canDelete, activePos = [], onGeneratePO, onEdit, onClose }) {
  const { showToast } = useToast();
  const confirm = useConfirm();
  const setStatus = useSetPRStatus({
    onSuccess: (r) => { showToast(`${r.prNumber} ${r.status.toLowerCase()}`, "success"); onClose(); },
    onError: (e) => showToast(e.message, "error")
  });
  const del = useDeletePurchaseRequest({
    onSuccess: () => { showToast(`${pr.prNumber} deleted`, "success"); onClose(); },
    onError: (e) => showToast(e.message, "error")
  });
  const busy = setStatus.isPending || del.isPending;

  useEffect(() => {
    const onKey = (e) => { if (e.key === "Escape") onClose(); };
    document.addEventListener("keydown", onKey);
    return () => document.removeEventListener("keydown", onKey);
  }, [onClose]);

  const reject = async () => {
    const ok = await confirm({ title: `Reject ${pr.prNumber}?`, body: `${pr.category} request from ${pr.requestedBy}.`, confirmLabel: "Reject" });
    if (ok) setStatus.mutate({ id: pr.id, status: "Rejected" });
  };
  const remove = async () => {
    const ok = await confirm({ title: `Delete ${pr.prNumber}?`, body: "This permanently removes the request.", confirmLabel: "Delete" });
    if (ok) del.mutate(pr.id);
  };
  const download = () => { if (!printPR(pr)) showToast("Allow pop-ups to download the PR", "error"); };

  return (
    <div style={{ position: "fixed", inset: 0, background: "rgba(15,23,42,0.45)", display: "flex", alignItems: "center", justifyContent: "center", zIndex: 1000, padding: 16 }}
      onClick={onClose} role="dialog" aria-modal="true" aria-label={`Purchase request ${pr.prNumber}`}>
      <div className="table-card" style={{ maxWidth: 620, width: "100%", padding: "var(--sp-20)", maxHeight: "90vh", overflowY: "auto" }}
        onClick={(e) => e.stopPropagation()}>
        <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", gap: "var(--sp-12)", marginBottom: "var(--sp-16)" }}>
          <div style={{ display: "flex", alignItems: "center", gap: "var(--sp-10)" }}>
            <span className="mono cell-tag" style={{ fontSize: "1.05rem" }}>{pr.prNumber}</span>
            <PRStatusPill status={pr.status} />
          </div>
          <div style={{ display: "flex", gap: "var(--sp-8)", alignItems: "center" }}>
            <button type="button" className="btn btn-secondary btn-sm" onClick={download}><Icon d={ICONS.download} size={13} /> Download PR</button>
            <button type="button" className="icon-btn" onClick={onClose} aria-label="Close"><Icon d={ICONS.close} size={16} /></button>
          </div>
        </div>

        <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(180px, 1fr))", gap: "var(--sp-12)" }}>
          <Field label="Requested by">{pr.requestedBy}</Field>
          <Field label="Department">{pr.department ? <DeptBadge dept={pr.department} /> : "—"}</Field>
          <Field label="Category">{pr.category}</Field>
          <Field label="Required by">{fmtDate(pr.requiredBy)}</Field>
          <Field label="Estimated cost">{fmtMoney(pr.estimatedCost)}</Field>
          <Field label="Suggested vendors">{pr.suggestedVendors || "—"}</Field>
          <Field label="Raised on">{fmtDateTime(pr.createdAt)}</Field>
        </div>
        <div style={{ marginTop: "var(--sp-14)" }}>
          <div className="field-label">Business purpose</div>
          <div className="field-value" style={{ whiteSpace: "pre-wrap", marginTop: 4 }}>{pr.businessPurpose}</div>
        </div>

        <PRAttachmentsPanel pr={pr} canManage={canManage} />

        <div style={{ display: "flex", gap: "var(--sp-8)", justifyContent: "flex-end", alignItems: "center", marginTop: "var(--sp-20)", borderTop: "1px solid var(--border)", paddingTop: "var(--sp-14)" }}>
          {(pr.status === "Pending" && canManage) || (pr.status === "Approved" && activePos.length) || canDelete ? (
            <div style={{ display: "flex", gap: "var(--sp-8)", alignItems: "center", marginRight: "auto" }}>
              {pr.status === "Pending" && canManage ? (
                <button type="button" className="btn btn-secondary btn-sm" disabled={busy} onClick={() => onEdit(pr)}>
                  <Icon d={ICONS.edit} size={13} /> Edit
                </button>
              ) : null}
              {pr.status === "Approved" && activePos.length ? (
                <span className="cell-muted">
                  {activePos.length === 1 ? "Linked PO: " : `Linked POs (${activePos.length}): `}
                  {activePos.map((po, i) => (
                    <React.Fragment key={po.id}>
                      {i > 0 ? ", " : ""}<span className="mono">{po.poNumber}</span> · {po.status}
                    </React.Fragment>
                  ))}
                </span>
              ) : null}
              {/* Delete is santosh-only (canDelete) and, unlike every other action here, works
                  regardless of status — a decided/old PR can still be removed by that one account. */}
              {canDelete ? (
                <button type="button" className="btn btn-secondary btn-sm" disabled={busy} onClick={remove}>Delete</button>
              ) : null}
            </div>
          ) : null}
          {pr.status === "Pending" && canApprove ? (
            <React.Fragment>
              <button type="button" className="btn btn-secondary btn-sm" disabled={busy} onClick={reject}>Reject</button>
              <button type="button" className="btn btn-primary btn-sm" disabled={busy}
                onClick={() => setStatus.mutate({ id: pr.id, status: "Approved" })}>
                {setStatus.isPending ? "Saving…" : "Approve"}
              </button>
            </React.Fragment>
          ) : null}
          {pr.status === "Approved" && canManage ? (
            <button type="button" className="btn btn-primary btn-sm" onClick={() => onGeneratePO(pr)}>
              {activePos.length ? "Generate another PO" : "Generate PO"}
            </button>
          ) : null}
          <button type="button" className="btn btn-secondary btn-sm" onClick={onClose}>Close</button>
        </div>
      </div>
    </div>
  );
}

function PurchaseRequestsPage({ canManage, canAdmin, canApprove, canDelete, initialFilter }) {
  const [filter, setFilter] = useState(initialFilter || "All");
  const [formOpen, setFormOpen] = useState(false);
  const [selected, setSelected] = useState(null);       // PR being reviewed in the modal
  const [editingPR, setEditingPR] = useState(null);      // PR being edited (Pending only)
  const [generatingFor, setGeneratingFor] = useState(null); // PR we're generating a PO from
  const { data: rows = [], isLoading } = usePurchaseRequests(filter === "All" ? {} : { status: filter });
  // map each PR to ALL its active (non-cancelled) POs — a PR can back more than one PO
  // (split/partial fulfillment), so the modal lists every linked PO, not just the first.
  const { data: pos = [] } = usePurchaseOrders();
  const activePosByPr = {};
  for (const po of pos) { if (po.status !== "Cancelled") (activePosByPr[po.prId] = activePosByPr[po.prId] || []).push(po); }

  return (
    <React.Fragment>
      <div className="page-head">
        <h1 className="page-title">Purchase Requests</h1>
        <p className="page-caption">Raise, review &amp; approve procurement &amp; service requests</p>
      </div>

      <div className="audit-filters">
        {FILTERS.map((o) => (
          <button type="button" key={o}
            className={"audit-chip" + (filter === o ? " audit-chip-on" : "")}
            onClick={() => setFilter(o)}>{o}</button>
        ))}
        <span className="audit-count">{rows.length} {rows.length === 1 ? "request" : "requests"}</span>
        {canManage && !formOpen ? (
          <button type="button" className="table-add-btn" style={{ marginLeft: "auto" }} onClick={() => setFormOpen(true)}>
            <Icon d={ICONS.plus} size={13} /> New Request
          </button>
        ) : null}
      </div>

      {formOpen ? <NewRequestForm onClose={() => setFormOpen(false)} /> : null}

      {isLoading ? (
        <div className="table-card"><div style={{ padding: "var(--sp-16)" }}><SkeletonTable rows={5} cols={7} /></div></div>
      ) : rows.length === 0 ? (
        <div className="table-card">
          <div className="empty-state">
            <div className="empty-icon"><Icon d={ICONS.template} size={20} /></div>
            <div className="empty-title">No purchase requests{filter !== "All" ? ` (${filter})` : ""}</div>
            <div className="empty-sub">{canManage ? "Click “New Request” to raise one." : "Requests raised by the IT team will show here."}</div>
          </div>
        </div>
      ) : (
        <div className="table-card">
          <div className="table-scroll">
            <table className="data-table">
              <thead>
                <tr>
                  <th><span className="th-plain">PR #</span></th>
                  <th><span className="th-plain">Requested by</span></th>
                  <th><span className="th-plain">Department</span></th>
                  <th><span className="th-plain">Category</span></th>
                  <th><span className="th-plain">Purpose</span></th>
                  <th><span className="th-plain">Required by</span></th>
                  <th><span className="th-plain">Est. cost</span></th>
                  <th><span className="th-plain">Status</span></th>
                  <th><span className="th-plain">Actions</span></th>
                </tr>
              </thead>
              <tbody>
                {rows.map((pr) => (
                  <tr key={pr.id} onClick={() => setSelected(pr)} style={{ cursor: "pointer" }} title="Open to review">
                    <td><span className="mono cell-tag">{pr.prNumber}</span></td>
                    <td>{pr.requestedBy}</td>
                    <td>{pr.department ? <DeptBadge dept={pr.department} /> : <span className="cell-muted">—</span>}</td>
                    <td>{pr.category}</td>
                    <td style={{ maxWidth: 240, whiteSpace: "nowrap", overflow: "hidden", textOverflow: "ellipsis" }}>{pr.businessPurpose}</td>
                    <td className="cell-muted">{fmtDate(pr.requiredBy)}</td>
                    <td>{pr.estimatedCost != null ? <span className="mono">{fmtMoney(pr.estimatedCost)}</span> : <span className="cell-muted">—</span>}</td>
                    <td><PRStatusPill status={pr.status} /></td>
                    <td>
                      <button type="button" className="btn btn-secondary btn-sm"
                        onClick={(e) => { e.stopPropagation(); setSelected(pr); }}>
                        {canApprove && pr.status === "Pending" ? "Review" : "View"}
                      </button>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      )}

      {selected ? (
        <PRDetailModal
          // Re-derive from the live list by id so attachment/status changes (which invalidate the
          // ["purchase-requests"] query) show up immediately without closing and reopening the modal.
          // Falls back to the originally-clicked row if it's fallen out of the current status filter.
          pr={rows.find((r) => r.id === selected.id) || selected}
          canAdmin={canAdmin} canManage={canManage} canApprove={canApprove} canDelete={canDelete}
          activePos={activePosByPr[selected.id] || []}
          onGeneratePO={(pr) => { setSelected(null); setGeneratingFor(pr); }}
          onEdit={(pr) => { setSelected(null); setEditingPR(pr); }}
          onClose={() => setSelected(null)} />
      ) : null}
      {editingPR ? <PREditModal pr={editingPR} onClose={() => setEditingPR(null)} /> : null}
      {generatingFor ? <POGenerateForm pr={generatingFor} onClose={() => setGeneratingFor(null)} /> : null}
    </React.Fragment>
  );
}

export { PurchaseRequestsPage };
